### ISSUE TITLE
Not quite issue but question / request

### ISSUE THREAD

**Issue by kalekje** [sabrogden/Ditto#11]
Hello,

Is it possible to assign tags to custom group text, such that it appears in the results when I search for the tag? 

That way, when I search for say "shrug", this saved text can appear in the results: ¯\_(ツ)_/¯ because I've assigned the tag 
"shrug" to that save. Perhaps alias is another way of phrasing it.

For more practical purposes, I have a bunch of order numbers for my job that I don't want to remember.

Thank you for your great work, I enjoy using Ditto and the Windows clipboard can't hold a candle to it.

**Comment by sabrogden** [comment]
You can change the title of any clip in the clip properties (alt-enter).  This is the text that is searched and displayed, not what is pasted.  So you can change the title to be "shrug - ¯_(ツ)_/¯',  You can now search for shrug but ¯_(ツ)_/¯ will be pasted.

**Comment by kalekje** [comment]
Thanks, that's a good solution! I still think adding tags to the properties would be a nice feature. Cheers!
