### ISSUE TITLE
Running under Vista

### ISSUE THREAD

**Issue by zino113** [sabrogden/Ditto#117]
Hi -
Tried latest version v3.24.184.0_32 today only to find out that there was an issue with Vista (Business) USER32.DLL and program did not start; had to revert to version v3.21.223.0 ... ( something to do with an entry point not found).
Could you please have a look into that?
Thanks, and
Best regards
-M

**Comment by Eagle3386** [comment]
Given it's a missing entry point issue in `User32.dll` which is part of the OS, there's nothing @sabrogden can do about it, you have to upgrade your OS - given that Vista is unsupported by Microsoft since more than 4 years now, it's more than about time to do that.

**Comment by zino113** [comment]
Granted that the OS is ageing (and I'm not here to argue as you got a point there) -- would you be able to point me to a place (link) where I could download _earlier_ versions to try out which will be the latest capable running under Vista? -M

**Comment by Eagle3386** [comment]
No, it's not aging. It's outdated! It's full of bugs! And - most importantly - it's full of security flaws!
Any single security flaw for itself is enough for not using it any _second_ longer than required to get a Win10 product key for about ~10-20 € from a serious eBay seller while simultaneously getting the ISO from Microsoft & creating a bootable USB drive from it.

Now, I'm still here to help, so here's the release folder: https://sourceforge.net/projects/ditto-cp/files/Ditto/

**Comment by zino113** [comment]
(This machine is still running a customer's proprietary software which even refused to properly run on a virtual machine. For my daily work I'm using W10 machines set up exactly the way you suggested in your post.)

Thanks for the releases link.

From testing I gather that v3.22.20.0 seems to be the last one, installing & running under Vista Business (32-bit) without error (fwiw, screenshots from v3.22.88.0 attached).

![vista_error_v3-22-88_2021-05-08_0](https://user-images.githubusercontent.com/20226105/117529717-9f8bee80-afc8-11eb-9c4b-a4924675b9bd.png)
![vista_error_v3-22-88_2021-05-08_1](https://user-images.githubusercontent.com/20226105/117529718-a0248500-afc8-11eb-87b2-ae5da666528d.png)
![vista_error_v3-22-88_2021-05-08_2](https://user-images.githubusercontent.com/20226105/117529719-a0bd1b80-afc8-11eb-880c-c5c3fed2e260.png)
