### ISSUE TITLE
Can ditto paste down a list?

### ISSUE THREAD

**Issue by newusersayshi** [sabrogden/Ditto#128]
I'm looking for a tool that can copy mutliple cells from an excel, e.g a whole column, then paste these one by one into an online software I am using, such that the first time I press the paste hot key (e.g ctrl + v), it pastes the first item, then the next time I press the hot keys it pastes the second item, then the next time third item and so on until I reach the end of the list. Is Ditto able to do this?

**Comment by sabrogden** [comment]
Sorry Ditto will not accomplish this.
