### ISSUE TITLE
Ditto is emptied at irregular intervals!?

### ISSUE THREAD

**Issue by norbertmuellerbaggen** [sabrogden/Ditto#133]
I have the strange effect that the memory of Ditto is now and then completely emptied, even the spanned entries are then gone. I do not know the cause, but I suspect "AVG TuneUp" to "clean" data here. Is this situation known or is there something I can do about it?
Thanks in Advance, Best Regards
Norbert

**Comment by sabrogden** [comment]
It's definitely a possibility that avg could be the deleting things.  Check the location of your db, are there any old copies of your db listed.  I've never used avg tuneup so can't be for sure, check avg for any settings documentation on what they cleanup.
