### ISSUE TITLE
What is the maximum number of saved copies?

### ISSUE THREAD

**Issue by grahamhammond** [sabrogden/Ditto#136]
I see the default is 500 but what is the realistic maximum - or is it no limit but obviously it's taking up space? Thanks

**Comment by sabrogden** [comment]
Really you are only limited by your hard drive space.  Behind the scenes Ditto use an sqlite database to store it's clips and this scales really well.  I have a coworker that has over 100,000 clip and says it works great.  You can go to options - stats to see how many clips and your database size.

Personally i keep 5000 clips, i feel after that it gets hard to find anything. 

Clips that are in groups, marked as never auto delete, have shortcut keys or are sticky will not be auto deleted so if you know you will need something you can set it to never auto delete.
