### ISSUE TITLE
I wish to paste the last three items I have copied at once.

### ISSUE THREAD

**Issue by belandresw** [sabrogden/Ditto#138]
Hello and Good Day!

I recently installed and used your Ditto clipboard manager and it works great!
However, I'm still figuring out on how to paste the last three items I have copied at once because I am working on data in excel.
I hope you could share your ideas here with me. 

Thanks in advance!

**Comment by sabrogden** [comment]
Select the rows you want to paste together and hit enter.  This will merge all the selected clips into a single paste

**Comment by mlucido679** [comment]
I cant get this to work. Only pastes 1st one
