### ISSUE TITLE
question: is it possible to send clips to ditto using curl? 

### ISSUE THREAD

**Issue by whudwl** [sabrogden/Ditto#140]
For example, I have another machine running Linux, sometimes I want to send a clip from the Linux machine to a Windows machine, since I cannot run ditto on Linux, I was wondering if I can somehow use curl to do it?

**Comment by sabrogden** [comment]
This can't be done.  Even if Ditto could send something over curl there would need to be something on the other side to receive and interpret that data.

**Comment by whudwl** [comment]
Seems I didn't phrase my question clear enough. Below is some more explanation. (if this still doesn't make sense please ignore) 
ditto does listen for connections when the "friends" feature is used, right? I imagine the "friends" feature is for one ditto instance to send clips to another ditto instance.
it's like ditto.exe --->clip--->another ditto.exe 
instead of that, I was wondering if I can do curl.exe --> clip --> ditto.exe
