### ISSUE TITLE
Captured Images in Ditto, Please Allow Enlarged View

### ISSUE THREAD

**Issue by nkormanik** [sabrogden/Ditto#142]
I have a list of images captured in Ditto.  The images appear a bit smaller than optimal (for me).  Please allow for option of enlarging the view seen of the images captured.  Perhaps 125% of present view would be optional in my case.

Thanks!
Nicholas Kormanik

**Comment by sabrogden** [comment]
Are you talking about the thumbnail view?  That will be as tall as your row so if you show more lines it will be bigger.  Use F3 on the row to view a large image you can zoom in/out on by mouse clicking or by mouse scrolling.
