### ISSUE TITLE
Can Ditto override Windows' native Win+V key?

### ISSUE THREAD

**Issue by thanhtacles** [sabrogden/Ditto#143]
From what I understand, most win keys are system wide low level priorities. Can Ditto replace this win v key altogether? It would be a better upgrade, since Microsoft can't seem to figure out how to copy URLs into the clipboard history for some reason.

**Comment by sabrogden** [comment]
You can achieve this with AutoHotKey, https://www.autohotkey.com/

The script would be

```
^v::
   MsgBox, Yes, Win+Ctrl+V works!
Return
```

**Comment by jdmarch** [comment]
Also Power Toys Keyboard manager can do this
![image](https://user-images.githubusercontent.com/278873/191364996-9b581453-2ae7-4e9b-b886-91b2315d6da4.png)
