### ISSUE TITLE
Features invalid Bug!

### ISSUE THREAD

**Issue by y761350477** [sabrogden/Ditto#145]
According to the description, this function should be the content of the copy text file, but I have no effect.

I have the function in the beta version of the previous test in my impression, but now he can't work properly!

![](https://y76.oss-cn-beijing.aliyuncs.com/20210618153722.png)
![](https://y76.oss-cn-beijing.aliyuncs.com/20210618153647.png)

**Comment by sabrogden** [comment]
Hard to say what is in that clip.  Look at the clip properties, what formats are in the clip.  It looks like it's just the text "File Contents - D:\Desktop\1.txt".  Where did you copy the clip from?  Was it from file explorer?

**Comment by sabrogden** [comment]
It should be the contents of that file.  This is how it works.

1. You copied the file D:\Desktop\1.txt
2. In Ditto you selected Save copied file (cf_hdrop) contents into Ditto or right click import/export - Import contents from cf_hdrop
3. Ditto read that file and save the contents of the file into Ditto's database as bytes
4. You can now go delete that file
5. When that clip is pasted Ditto will write the contents of the original file to a temp file and then set the contents of the clipboard to the location of the temp file created so it's like you are pasting the original file even though it was deleted.
6. Now that clips can be pasted into file explorer or anything that accepts file pastes.
