### ISSUE TITLE
[bug ?] delete key vs arrow key up/down

### ISSUE THREAD

**Issue by KamelittaOida** [sabrogden/Ditto#147]
hello

Version 03.24.184.00 64bit

Why does the delete key not repeat its action when pressed? It just deletes once and it is then blocked.
Unlike the arrow keys.
I only found 'Send Keys Delay (ms)' but nothing about the delete key, to enable it. ?

**Comment by sabrogden** [comment]
I tried playing around with enabling this and I didn't like it, it just flew through the list with no way to control or understand what you were deleting.  So I'm not going to enable it.  You can shift - up/down keys to select multiple rows and then delete them.  Tried this in file explorer and it doesn't handle repeat delete keys.
