### ISSUE TITLE
Ditto Server

### ISSUE THREAD

**Issue by christianromeni** [sabrogden/Ditto#148]
It would be awesome to have a package of a ditto Server (docker, exe, etc) that can be run on different systems (for example my Synology NAS or Pie) and have a history of everything copied, to be shared between different PC's that login to this server.
There already is a similar function, but I would like to have it as a service that always runs on one central device...

Is something like that already possible? Would it not be cool to have it?

Best regards.

**Comment by sabrogden** [comment]
Sounds awesome but not plans to do anything like that.
