### ISSUE TITLE
Database Recovery

### ISSUE THREAD

**Issue by Chaython** [sabrogden/Ditto#149]
There was an issue with windows where I clean installed, then when I readded my database, it loaded no clipboard history.
The file is still intact[more than 16gb], and adding clips, makes the file bigger.
How can I restore the old clips?

**Comment by sabrogden** [comment]
Looks like you will need to try and restore the sqlite db.  Look in options - general - database path and go to that location and make a backup of your db.  Then try some of the steps listed here, https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database/57872238#57872238 or https://www.google.com/search?q=fix+corrupt+sqlite+database

Hopefully one of these works then go back into options and select the fixed db.

**Comment by Chaython** [comment]
> @sabrogden I had the same issue aound end of June. I think it was caused by choco update? Not too sure. Anyways, I lost also settings, are they also recoverable somehow? And is the default limit of 500 a hard limit or how does it work? Is anything above that completely gone?

I know you can have far more than 500, in my last purge 918 screenshots alone [CF_DIB]
In the options there is a time and history limit 
![image](https://user-images.githubusercontent.com/6486343/147377643-1f5595a8-0953-4b15-8106-9240b30fbac1.png)
As stated in the OP I had over 16gb of history....
I never figured how to recover/repair/defragment the db

**Comment by Ronnie2309** [comment]
> Looks like you will need to try and restore the sqlite db. Look in options - general - database path and go to that location and make a backup of your db. Then try some of the steps listed here, https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database/57872238#57872238 or https://www.google.com/search?q=fix+corrupt+sqlite+database
> 
> Hopefully one of these works then go back into options and select the fixed db.

I'm facing quite similar problem but i deleted my important entries with junk by myself few days before
after deleted i realized that i did something wrong and now i want my Ditto clipboard entries back
i get the "Ditto.db" file as per your earlier instruction please guide me for next steps in a easy way
i've downloaded the (DB Browser for SQLite) windows software but i don't understand what to do with
please help me ASAP i really need that clipboard entries.
