### ISSUE TITLE
Regression: Typing in search box doesn't always work anymore

### ISSUE THREAD

**Issue by SanderBouwhuis** [sabrogden/Ditto#152]
I have this clip stored (as never auto delete):
```
<UNDER CONSTRUCTION>

</UNDER CONSTRUCTION>
```
Since the last version, I cannot type '<u' anymore when showing the clips because the '<' character is not placed into the search box anymore.

Steps to reproduce:
1. Make sure you have a clip that contains '<u'.
2. Press the shortcut to show the 'Quick paste' window.
3. Type '<u'.
4. The search box will now only contain 'u' instead of '<u'

In the previous version this used to work, but now no longer ;-(

Please fix!

**Comment by detzt** [comment]
While < is working for me, I cannot start searching with uppercase letters and these symbols: !?'">{}[]/\=%$,.;:* 
Strangely a few symbols are working for me, namely <#+-

**Comment by SanderBouwhuis** [comment]
You are right!!!

It's the <SHIFT> key that causes trouble. You cannot start ANY search where you need the SHIFT key.
Please fix this regression.

**Comment by sabrogden** [comment]
This is fixed in the latest beta, https://ditto-cp.sourceforge.io/beta/

**Comment by SanderBouwhuis** [comment]
I wanted to download the beta, but it says this on the download page:
"Artifacts older than 1 month are automatically deleted"

Does that mean Ditto automatically uninstalls after a month? Or that the version stops working?!?
That's not what I want.

**Comment by garoto** [comment]
> Does that mean Ditto automatically uninstalls after a month? Or that the version stops working?!?
That's not what I want.

No, that means that older builds by the CI expires after a month. It has nothing to do with your local copy of the program.
