### ISSUE TITLE
Is it possible to exclude a whole app and not just a "text" from the app? (e.g. KeePassXC, Password manager)

### ISSUE THREAD

**Issue by TobiasDev** [sabrogden/Ditto#153]
Hello! 
I tried reading the docs but I could have missed if you had this written there. Is it possible to exclude everything copies from a certain app? 

I use KeePassXC for my passwords and I would like to not include these in the clipboard manager (when I copy a password from that app). Is this possible?

**Comment by leaumar** [comment]
Is this not sufficient in your case? Works for me, though I rarely let keepass copy to clipboard to begin with.

![image](https://user-images.githubusercontent.com/3950300/124909811-2f5f1080-dfeb-11eb-9e67-032b27d80db5.png)

**Comment by TobiasDev** [comment]
Oh, I didn't see that was a thing!!! I missed that one. Sorry! That looks exactly what I need.

**Comment by TobiasDev** [comment]
> Is this not sufficient in your case? Works for me, though I rarely let keepass copy to clipboard to begin with.

Actually, I never thought about that. To not add it to the clipboard at all.

**Comment by leaumar** [comment]
Glad to help. It takes some elbow grease to set up form autofill or autotyping the way you need it sometimes, but it's so worth it, not only for the security benefit.

**Comment by TobiasDev** [comment]
Sorry! Of-course, closing with this comment. :)
