### ISSUE TITLE
Copies missed if they happen too quickly in sequence

### ISSUE THREAD

**Issue by leaumar** [sabrogden/Ditto#154]
My screenshot tool is set to copy first the captured image to clipboard, followed by a public hotlink to it. For around the past two years or so, I've had the issue that the hotlink would be on the system clipboard but often not detected by ditto (not recorded in its history), until I artificially added a delay between the image copy and hotlink copy.

I've kinda lost the option to have that delay now, so I'm more motivated to bring it up here now. ^^' It wasn't a problem back when I used less performant upload services so that there was a natural delay.

I've looked around the settings but can't seem to find anything that would relate to a cooldown period between copy detections. There's the advanced setting "copy and save clipboard delay" but I don't know what it does and setting it to 0 (from 1000) doesn't help anyway.

I've been using copyq since yesterday for comparison and it has no trouble reliably detecting both the image and hotlink every time. FYI my upload service is now a NAS on wired LAN, so despite there being an http (or even ftp actually) call involved, the delay is extremely short.

Is there anything I've missed in the settings that would solve this, or does ditto systemically have trouble keeping up with rapid copies?

**Comment by garoto** [comment]
I think I figured it out:

In previous Ditto versions, there used to be a GUI option called _**"Ignore copies that occur X milliseconds from the last copy (1000 ms = 1 sec)"**_:

![screenshot-0715-08-07-2021](https://user-images.githubusercontent.com/11768175/124971039-1ceed200-dfff-11eb-8971-10baeff880b1.png)

With the general app redesign circa 2018(?), that option wasn't included in the new GUI layout or in hte Advanced options dialog (AFAIK), but it remained in the registry and will be properly parsed and applied by the program if present.

The property is located at `HKEY_CURRENT_USER\Software\Ditto` and is called `SaveClipDelay` and has a default value of 500(ms). Can't say anything about how a portable config would look like.

**Comment by garoto** [comment]
@leaumar 
Can you confirm messing with `SaveClipDelay` values in the registry fix the behavior you observed?

**Comment by leaumar** [comment]
It does appear to, thanks. Would be best if the dev restored the option though, I guess that'll be the point of this ticket.

**Comment by garoto** [comment]
Alright, thanks. Pinging @sabrogden.

**Comment by sabrogden** [comment]
https://ditto-cp.sourceforge.io/beta/

Added into the advanced options

![image](https://user-images.githubusercontent.com/16867884/126023757-8119224a-2828-428c-8abc-3da0f02b6038.png)
