### ISSUE TITLE
Flag send paste disabled not working (version 3.23.124)

### ISSUE THREAD

**Issue by xPudda** [sabrogden/Ditto#17]
In the 3.23.124 Ditto version i have disabled the flag **"Send paste (otherwise it will just load...)"**:

![image](https://user-images.githubusercontent.com/24530984/101611732-27fe6700-3a0a-11eb-8d51-c937a9c1903a.png)

But when i select a row to just copy it in the clipboard, it paste it as well.

Here you are:

![test](https://user-images.githubusercontent.com/24530984/101612492-fcc84780-3a0a-11eb-86c7-c653071926b4.gif)

**Comment by scottbrogden-iheartmedia** [comment]
That setting in config is only used when pasting from last ten rows hotkeys.  

To not have Ditto send the paste after normal selection go to options - general - advanced, set "Paste clip in active window after selection" = False.  Another option is to press ctrl-c on a row, this will copy the selected clip but not paste it.

![image](https://user-images.githubusercontent.com/74422469/101695188-6e1af100-3a31-11eb-862b-d6934b7f0739.png)
