### ISSUE TITLE
[BUG] Latest 64bit portable version of Ditto is unable to change the theme and language.

### ISSUE THREAD

**Issue by Dhyfer1** [sabrogden/Ditto#173]
Hi dev.

I have downloaded the latest portable beta version of Ditto for my 64bit system and it works fine, except for two things:

1. Every time I try to change Ditto's language, I get an error message
2. I have some themes that I have created and placed them in the Themes folder, but they do not appear along with the Ditto built-in themes, and if I change a built-in theme to another built-in theme (only two built-in themes appear in the Ditto settings: 'Ditto' and 'Follow windows light/dark themes') an error message appears. As can be seen, when changing from one integrated theme to another in the settings, the change is not reflected and Ditto remains the same.

In the attached video you can see the error message I am talking about (open the video in a new tab to see it in more detail), is there any solution to that message?

![Animation13](https://user-images.githubusercontent.com/50301201/129637427-5ad2253c-314f-4765-a39c-8555b502ee7c.gif)

The above mentioned happens on Windows 10 64bits with the latest portable beta version of Ditto (version 3_24_210_0).

**Comment by OmarNamis** [comment]
Hi @Dhyfer1 !
I just tested the latest beta, and it's working fine for me.

Is this issue reproducible for you with the stable version?

**Comment by sabrogden** [comment]
How are you starting Ditto.  From a shortcut?  From windows auto start?  I'm seeing this work correctly. Wondering if it's a current directory issue?  What if you go double click on Ditto.exe, see any difference.

**Comment by Dhyfer1** [comment]
> Hi @Dhyfer1 !
> I just tested the latest beta, and it's working fine for me.
> 
> Is this issue reproducible for you with the stable version?

Hi @OmarNamis.

With the portable version of the latest stable version (3.24.184.0) the same thing is happening, I get the same error :(


> How are you starting Ditto. From a shortcut? From windows auto start? I'm seeing this work correctly. Wondering if it's a current directory issue? What if you go double click on Ditto.exe, see any difference.

Hi @sabrogden 

I have deleted all registry entries related to the latest portable beta version, then downloaded and unzipped the latest stable beta version (also portable). All my portable programs are in a subfolder called PortApps inside the downloads folder, so the Ditto executable is in this path:

`"C:\Users\diego\Downloads\💼PortApps\DittoPortable_64bit_3_24_184_0\Ditto\Ditto.exe"`

Then I start ditto by double clicking on its executable, change the language of the app and/or change the theme and then the error I mentioned before appears, so there is no difference, the error is the same on my system.
How I start Ditto? I have configured Ditto to start every time the system starts with the option: 'Start Ditto on system startup' in the General tab under 'Options'. When Ditto starts at system startup, its icon appears in the system tray, and I call Ditto with the combination <kbd>Ctrl</kbd>+<kbd>ñ</kbd> because my keyboard is Spanish.

I don't have any shortcuts, Ditto just runs by itself at every login.

**Comment by OmarNamis** [comment]
I see what's happening here, you have ditto inside a folder with an emoji in its name "💼PortApps" and this is what's causing the issue.

**Comment by Dhyfer1** [comment]
> I see what's happening here, you have ditto inside a folder with an emoji in its name "💼PortApps" and this is what's causing the issue.

Wow my friend!  Thanks a lot! I never thought that a simple emoji was the problem. So I have renamed the folder to just 'PortApps' and my problem is gone. 

@sabrogden I already fixed my problem, I just had to rename the folder without the emoji thanks to the answer from @OmarNamis so this issue can be closed.

Thanks a lot. 😊

**Comment by sabrogden** [comment]
Great you got it working.  Fixed in the latest https://ditto-cp.sourceforge.io/beta/ if you want to go back to that folder name.
