### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by hueldoeu** [sabrogden/Ditto#175]
i get a notification from ditto everytime the computer restarts or if i restart ditto. i can disable it here:

windows 10 => settings => system => notifications and actions => and disable ditto notifications 

but i would like to know if there is something in the settings menu of ditto. i am using windows 10 x64 all updates.
![Screenshot 2021-08-18 152027](https://user-images.githubusercontent.com/11273667/129911891-8313c7a7-a353-45a3-b8e8-746adbeb219f.png)

**Comment by sabrogden** [comment]
Right click on Ditto's task bar icon - Show startup message

![image](https://user-images.githubusercontent.com/16867884/129917969-95d12a7c-fb7a-4224-8809-5ef58779267f.png)
