### ISSUE TITLE
Distinuishing between Clips

### ISSUE THREAD

**Issue by Patches99** [sabrogden/Ditto#186]
How can I better define each clip? When I look at the list it would be nice to have a line between each clip or some other way to distinguish. Now there is a very faint gray in every other clip but it is not dark enough.

**Comment by seascape** [comment]
If none of the current color themes are to your liking, you can try tweaking an existing one to better suit you.

(You can change themes by going to Options -> General -> Theme.)

Example:
I did this by going into the \Themes subfolder, making a copy of `DarkerDitto.xml` renaming the copy, then editing it in a text editor. All colors are represented by trios of numbers, ranging from 0 to 255, that represent the levels of their Red, Green, and Blue components. The theme files are well labeled so it's fairly obvious which colors go with which UI elements.

Google has a [built-in color picker](https://www.google.com/search?q=rgb+color+picker) you can use if you're trying to find a certain color's RGB value.

Happily, Ditto seems to read its theme file every time you call it up, so after you save the .xml theme file you're editing, any changes will be reflected in Ditto the next time you summon it.

Attached is the quick edit I did to the dark theme to better suit my own preferences. It's a little less dark.
[NotQuiteAsDarkDitto.zip](https://github.com/sabrogden/Ditto/files/7274379/NotQuiteAsDarkDitto.zip)
