### ISSUE TITLE
Disabling automatic paste

### ISSUE THREAD

**Issue by shtras** [sabrogden/Ditto#195]
The option to just put a clip in the clipboard without auto pasting anywhere seems broken now with the introduction of the quick paste keyboard type of thing.
Back in version 3.21 there was a global setting checkbox "Paste Clip in active window after selection" which I could untick to achieve this.
The only way to do this in the current version is to remove all the shortcuts for the "Paste" action, and reassign them to the "Copy" action instead, but even then copying the clip doesn't change the order (the old version's "Update Clip Order On Paste" checkbox)
Is there a way to achieve this functionality now (copy, move to top, don't paste), or the only option is to find/build an older version?

**Comment by sabrogden** [comment]
Go to options - general - advanced - paste clip in active window after selection, set this to false

![image](https://user-images.githubusercontent.com/16867884/134786819-4e29f1a7-3df5-430b-a3d2-10a25bfccf47.png)

**Comment by shtras** [comment]
I totally missed that button that happens to be in plain sight. Thanks!
