### ISSUE TITLE
The search bar shows an error after using a shortcut key

### ISSUE THREAD

**Issue by Vzz1c** [sabrogden/Ditto#197]
When I use ctrl+d to delete data, the search bar displays the following problem
<img width="438" alt="image_23" src="https://user-images.githubusercontent.com/49944812/135566192-404d6367-e610-43ff-98ce-268a34393f45.png">

When I use the shortcut keys ctrl+L at random, the search bar shows the following problem
![image](https://user-images.githubusercontent.com/49944812/135566272-85e970c9-f362-4850-b9a8-3f69213b23d8.png)

**Comment by sabrogden** [comment]
First one is fixed in the latest, https://ditto-cp.sourceforge.io/beta/  second one i'm not sure on, seeing the same thing when pressing control + anything.

**Comment by Vzz1c** [comment]
> 第一个在最新版本中修复，https://ditto-cp.sourceforge.io/beta/ 第二个我不确定，按 control + 任何东西时看到同样的事情。

In fact, most of the shortcuts have some problems with strange characters or spaces

**Comment by Vzz1c** [comment]
还有一些快捷键会出现空字符

**Comment by Vzz1c** [comment]
There are also some ctrl that will appear as null characters
