### ISSUE TITLE
Feature Request: Replaceables

### ISSUE THREAD

**Issue by semuhphor** [sabrogden/Ditto#200]
Hi. I have used Ditto for years... great program.

I though about a feature i could use... replaceable values. 

If you paste a snippet that contains some type of replaceable indicator (e.g., $*ReplaceMe*$), it would ask for a value with a prompt similar to "Value for ReplaceMe:". The value would replace all instances of the $*ReplaceMe*$ string in the snippet with the value provided. 

I use Ditto to hold a list of pro-forma SQL scripts that require small changes each time they are run. A feature like this would be a great help.

Thank you for Ditto!

**Comment by sabrogden** [comment]
I could definitely see some use cases for this but no plans to implement this.  Thanks for the suggestion.
