### ISSUE TITLE
Check for Updates Button

### ISSUE THREAD

**Issue by P-rox-y** [sabrogden/Ditto#205]
Would be nice to have a "Check for Updates" or "Update" button on the About tab for Ditto so we don't have to check back to the repo for the latest builds.

**Comment by sabrogden** [comment]
No plans to implement this.  This can be achieved by using the Windows store version or chocolaty (https://community.chocolatey.org/packages/ditto/3.24.214.0) and then using the choco commands to find updates.

**Comment by nitesh-108** [comment]
The Windows version is 32 bit only.
