### ISSUE TITLE
Regex search should do searching, not full matching

### ISSUE THREAD

**Issue by Mattwmaster58** [sabrogden/Ditto#207]
When I search by regex, often I'm not looking for a full match, I'm simply looking for a substring match. For example, let's say I'm searching for these entries `dkfj_LAB2`, `dkfj_LAB5`, `dkfj_LAB8`,  I'd like to be able to simply type the following: `LAB\d`, however, this doesn't match anything, and to achieve my intended behavior, I'm forced to surround my regex search term with `.*` eg in the example before I type `.*LAB\d.*`, which yields the results I'd like.

I'm learning C++, so I'd love to try and make this change in the codebase myself and submit a PR, I was wondering if there's any pitfalls/reasons behind the design decisions, implementation preferences, etc before I dive in. Thanks!

**Comment by sabrogden** [comment]
I've changed the default regex to be a find rather than a match. https://ditto-cp.sourceforge.io/beta
