### ISSUE TITLE
Double clicking an entry in list asks for UAC

### ISSUE THREAD

**Issue by bmix** [sabrogden/Ditto#211]
I don't quite understand what could cause this, but often (not always), when I double click an entry in Ditto's listview I get an UAC dialog, asking me for admin permissions. This happens since many years, already, so it's not something new.

**Comment by sabrogden** [comment]
If you are pasting into an app that is running as Admin but Ditto is not running as admin then Ditto launches another instance of Ditto running as admin to perform the paste.  By default windows does not allow a non admin to talk to an admin running app, so this is trying to get around this to perform the paste.

**Comment by bmix** [comment]
Thank you. I could work around this by changing the action of double-click to just move the item to the top.
