### ISSUE TITLE
Ditto Clipboard

### ISSUE THREAD

**Issue by fkhan25** [sabrogden/Ditto#216]
We need to know where the files that are copied using Ditto being stored. Are they being copied and stored via a cloud app to the cloud or are they being downloaded locally on to a sql database on the user's desktop or machine? Do you have a security whitepaper?

**Comment by fkhan25** [comment]
It's been 5 days since I opened my issue/query however did not get a response. Please answer my query as soon as possible, we need to complete a risk assessment.

**Comment by garoto** [comment]
lol

**Comment by garoto** [comment]
Imagine writting the best opensource clipboard manager software for Window, distribute it freely for almost 20 years now and having to deal with useless queries/tickets like this. Holy shit.

**Comment by sabrogden** [comment]
Ha garoto :)

All data is stored in a local sqlite database on your machine.  Settings are stored in the registry.  Nothing is uploaded to the cloud.
