### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by icyhoty2k** [sabrogden/Ditto#218]
can you make an option to show lenght and words count in Ditto, i also need a way to view clipboard data by day maybe put some button or labels to filter by days

**Comment by sabrogden** [comment]
The latest, https://ditto-cp.sourceforge.io/ shows this data in the tooltip footer.  Currently there isn't a way to filter by the date.

![image](https://user-images.githubusercontent.com/16867884/141663852-baee0ce0-cd64-4205-8ee0-416c41e44ca8.png)

**Comment by icyhoty2k** [comment]
how can i leave the tooltip open all the time after showing and closing ditto by ctrl-`
