### ISSUE TITLE
Isn't there a function to delete all clipboard data with one click?

### ISSUE THREAD

**Issue by WuXianShanGuang** [sabrogden/Ditto#223]
I want to delete all clipboard data manually, but when I open the menu of cleaning clipboard, I need to manually select the date, format and title for selective deletion, which is so troublesome.

**Comment by Elehiggle** [comment]
Delete %appdata%\Ditto\Ditto.db

**Comment by WuXianShanGuang** [comment]
I found the remove all button in the Statistics menu item of the options window. The problem has been solved, thank you.
