### ISSUE TITLE
Ditto not pasting...

### ISSUE THREAD

**Issue by ScottsterUK** [sabrogden/Ditto#227]
I've used Ditto for years. I love it and without it my productivity is knocked. But... I simply cannot get it to paste on a new laptop. The tool is installed and copies just fine -- I can see all copied items in the list. But it simply will not paste selected items using shortcuts or the right-click Special Paste options.

I *can* drag items one at a time from the item list to whatever application but, clearly, that is not practical -- and now how Ditto should work.

I've tried both the x64 app and the Microsoft Store app and neither will paste on this new laptop. Ditto is still working fine for me on two other computers.

Any ideas?!

**Comment by DiggerP** [comment]
Hi, can you try Ctrl+V  ?
Helped me out in cases like this.

**Comment by sabrogden** [comment]
Try pasting into Notepad, does this work.  What app are you pasting into that is not working.  Is the clip on the clipboard, can you manually press ctrl-v and have it paste the data.

There is an option in options - general - advanced - "Paste clip in active window after selection", this should be set to True.

**Comment by ScottsterUK** [comment]
> Hi, can you try Ctrl+V ? Helped me out in cases like this.

Yes, this works (I discovered independently -- but thanks anyway). However, I often need to use Special Paste options on the right-click menu, so this isn't a great solution for me.

**Comment by ScottsterUK** [comment]
> Try pasting into Notepad, does this work. What app are you pasting into that is not working. Is the clip on the clipboard, can you manually press ctrl-v and have it paste the data.

Any/all apps, but mainly Microsoft Word and/or LibreOffice Writer. As above, I discovered that Ctrl+V *does* work but I need mainly to use the Special Paste right-click options, and these just do not work now.
 
> There is an option in options - general - advanced - "Paste clip in active window after selection", this should be set to True.

I checked. It is set to True. Thanks for the suggestion, though.

**Comment by sabrogden** [comment]
Try changing this value in options - general - advanced - activate window delay.  Try different values, maybe 500.  After selecting a clip, Ditto selects the prior active window to paste into then waits this long to simulate the ctrl-v being pressed.

![image](https://user-images.githubusercontent.com/16867884/146213759-102f07ea-ef48-4069-aa66-f0a2a9318af0.png)

**Comment by ScottsterUK** [comment]
> Try changing this value in options - general - advanced - activate window delay. Try different values, maybe 500. After selecting a clip, Ditto selects the prior active window to paste into then waits this long to simulate the ctrl-v being pressed.

Wow -- that appears to have done the trick! Interesting that on my old machines -- including one 14-year-old desktop -- it's set at the default of 100ms and works fine. However, on my new laptop (a not-cheap Core i7), it requires this 500ms delay. I can live with that, though.

Thank you VERY much. You've just rescued this little tool for me.

**Comment by ScottsterUK** [comment]
I just made a small donation incidentally, just by way of tangible thanks. ;)
