### ISSUE TITLE
Mapping keys to a literal string

### ISSUE THREAD

**Issue by galbaras** [sabrogden/Ditto#230]
This may be a usage question, but if not, it'll be a great feature.

I often need to search pages for "error" or "problem" or "bug" or "issue" or "problem" or "fail". I have a browser extension that can handle regular expressions, but whenever it's used, it starts with a blank search field, and I need to type "error|problem|bug|issue|fail" manually.

Is there a way to use Ditto to map a keyboard shortcut to a specific string?

If not, is there a way to save this string into a copy buffer, and remember it until it's overwritten?

**Comment by sabrogden** [comment]
A couple ways to accomplish this

1. Any clip can have a shortcut key assigned, this can be active when Ditto is open or it can be available globally.  So copy your text, open the clip properties and assign a hot key and check the "hotkey available globally".  Now you can press that hot key from any app and it will paste your text.

2. Just have the clip in Ditto (you can set it to never auto delete to always keep it around).  Open Ditto type problem to search and paste it.  You can change the clip description in the clip properties, this is the text that is displayed and searched, not the actual data that is pasted.  So you can change the title to "regex search".  Now you can search for "regex" and find your clip.

3. Set the clip and a sticky clip.  This will always show at the top of the list so it is easy to paste.

**Comment by galbaras** [comment]
Tried the first method. Brilliant. Thank you!
