### ISSUE TITLE
Ctrl-C intermittently doesn't work after an upgrade to Windows 10 21H2

### ISSUE THREAD

**Issue by rustyx** [sabrogden/Ditto#232]
A long-time Ditto user, _never_ had any issues running under Windows 10 x64.

But since the upgrade from 21H1 to 21H2, Ctrl-C doesn't work reliably anymore when Ditto is loaded; pressing Ctrl-C sometimes does absolutely nothing, the old value remains in the clipboard. Pressing it 2-3 times though always works.

When Ditto is shut down, the problem goes away.

Is this a known issues?

How to debug this?

**Comment by sabrogden** [comment]
Are other shortcut keys intermittent?  Try F3 to view the description, same?

**Comment by rustyx** [comment]
Every other shortcut is working fine.
Just to clarify, I'm talking about the built-in system Ctrl-C shortcut, which is supposed to copy text into the clipboard (for example, in Edge or vscode). I wonder if there's a debug log in Ditto where I can see if any event even reaches Ditto in this case?

**Comment by sabrogden** [comment]
Go to options - general - advanced - scroll to the bottom, "Write debug to file" = True.  This will write debug to the file, C:\Users\<user name>\AppData\Roaming\Ditto\Ditto.log.  Take a look at it, also post it back and i'll look also.

![image](https://user-images.githubusercontent.com/16867884/146650435-0feef54f-bc77-4b2f-9267-839a71ad6c5a.png)

**Comment by rustyx** [comment]
Here's the log from one incident. [Ditto_232.log](https://github.com/sabrogden/Ditto/files/7763705/Ditto_232.log)

At 15:40:57 copied "SetWindowTextA"
At 15:41:30 copied "https\://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowtexta"
At 15:41:35 copied "To set the text of a control in another process... " - this didn't work, the URL remained in the clipboard
At 15:44:39 copied "To set the text of a control in another process... " again, this time it worked

**Comment by sabrogden** [comment]
When you say the URL remained in the clipboard you are talking about the clip showing as the top clip in Ditto?  Or it was what was on the currently clipboard, pressing ctrl-v would paste the url?

at 15:41:35 i see https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowtexta#remarks copied not "To set the text of a control in another process... " 

at 15:44:40 i see "o set the text of a control in another process ..." copied.

**Comment by rustyx** [comment]
Both ctrl-v and Ditto window. So ctrl-v would paste the old content (the url indeed).

**Comment by sabrogden** [comment]
Well Ditto just follows the content of the clipboard, so if that is not changing then it won't show up in Ditto.

**Comment by rustyx** [comment]
OK it looks like the issue is elsewhere. Let's close this for now, I'll comment here if I find out more.
