### ISSUE TITLE
Set tags for text to facilitate searching

### ISSUE THREAD

**Issue by MAKER555** [sabrogden/Ditto#235]
Is it possible to add a label to each text like copyq? When searching, the label can also be searched. It is very convenient to use as a short shortcut key. I hope that ditto can add this function.

**Comment by sabrogden** [comment]
In the clip properties you can edit the description.  This is what is displayed in the list and what is searched, but not what is pasted, that can be edited by right clicking - edit clip.  So edit the description in the clip properties.  In the properties window you can set a shortcut key also.

**Comment by MAKER555** [comment]
Understand, I didn’t set the search method correctly before, which caused the content of [Quick Paste Text] to not be searched. Now it’s set up and it’s perfect. Thank you for your reply.谢谢你

> 在剪辑属性中，您可以编辑描述。这是列表中显示的内容和搜索的内容，而不是粘贴的内容，可以通过右键单击进行编辑 - 编辑剪辑。所以在剪辑属性中编辑描述。在属性窗口中，您也可以设置快捷键。
