### ISSUE TITLE
Feature to auto update

### ISSUE THREAD

**Issue by nitesh-108** [sabrogden/Ditto#238]
Please add an auto-update feature so that I don't have to manually check the version and download the setup file.

**Comment by dawidkolodziejczyk** [comment]
Would be very helpful.

**Comment by sabrogden** [comment]
No plans to do this.  This can be accomplished by using the windows store version or by installing via chocolaty, https://community.chocolatey.org/packages/ditto/3.24.214.0 and using chocolaty tools to keep it updated.
