### ISSUE TITLE
PasteSpecial > CamelCase

### ISSUE THREAD

**Issue by peter289** [sabrogden/Ditto#239]
![image](https://user-images.githubusercontent.com/60219592/148066243-df138c5b-c2aa-4780-8d68-202dcea994a0.png)

Is there a way to add "Paste CamelCase" to the paste special menu?
It should transform a sentence like this "This is a sentence" to this "ThisIsASentence"

It would be super useful for programmers

**Comment by sabrogden** [comment]
https://ditto-cp.sourceforge.io/beta

![image](https://user-images.githubusercontent.com/16867884/149646993-acd95894-4ecd-4a4d-961b-f91c35be28b0.png)

**Comment by peter289** [comment]
thanks a lot for the quick update:
somehow I cannot find it in the quick paste menu:
![image](https://user-images.githubusercontent.com/60219592/149727633-eb745a13-e856-4041-98e8-6f824dd0fb7a.png)

**Comment by sabrogden** [comment]
fixed to show in the shortcuts list, https://ditto-cp.sourceforge.io/beta

**Comment by peter289** [comment]
thanks, retested it with several strings and it works like a charm. thank you :)
