### ISSUE TITLE
Does Ditto have an "After Paste" function?

### ISSUE THREAD

**Issue by ahmedfarrag17** [sabrogden/Ditto#242]
For ex. I want to let Ditto execute a specific Action (a Shortcut, like Alt+X) immediately after Pasting in the current cursor position (in the opened software). 
if Yes, how to do it? and also can I assign it to ONLY a specific Group?

Thank you!

Update:
I discovered that we can add "On Paste" Scripts to execute some commands after Pasting. which is what I need.
but can someone write that Script for me? (A script where I specify the names of the Ditto Clipboard Groups and/or subgroups to which I apply that after pasting, do Alt+X shortcut!). 

Thanks to anybody who can help me with this!

**Comment by sabrogden** [comment]
The On Paste scripts are meant to adjust the data that is pasting, convert line feeds or replace text.  There currently isn't support for applying groups on paste or anything beyond adjust the data being pasted.
