### ISSUE TITLE
Ditto.db size is 6GB - how to compress or otherwise make it smaller

### ISSUE THREAD

**Issue by epifeny** [sabrogden/Ditto#250]
Is there a way I could compress or otherwise "remove/delete" data from it that is large and isn't needed?
Perhaps even when I copied a file, it was copied to the clipboard and hence into Ditto which made it what it is now.

**Comment by smbrannon** [comment]
> Is there a way I could compress or otherwise "remove/delete" data from it that is large and isn't needed? Perhaps even when I copied a file, it was copied to the clipboard and hence into Ditto which made it what it is now.

There are a couple of ways you can reduce the size of your Ditto database. One is to [limit the number of clips that are saved to the database. ](https://github.com/sabrogden/Ditto/wiki/Auto-Delete) Another would be to [limit the types of data that Ditto saves to the database.](https://github.com/sabrogden/Ditto/wiki/Excluding-clip-from-saving) Lastly, you can always scroll through the list of your clippings and manually delete them.

Also, Ditto doesn't store files you cut/copy from within the Explorer file manager, just the path info, so this isn't your issue.

Don't forget about the [Wiki](url); there's lots of useful info in there.

Hope this helps.

**Comment by epifeny** [comment]
Thanks for taking the time to reply! I appreciate it.
I would rather not limit anything nor filter what is being clipped. I'd rather be able to search my clips for the largest ones, and retrospectively decide what I need or don't need.

**Comment by sabrogden** [comment]
Right click on the task bar or the ... in Ditto - Delete clip data.  This lists each individual clip item of all clips. From here you can see the largest clip items, most likely it's going to be a bunch of CF_DIB items (images).  You can delete each item as needed from this window.

**Comment by SanderBouwhuis** [comment]
I just tried it, but it doesn't work.

When I open the 'Delete Clip Data' window and click on the 'Data Size' header the list is NOT sorted on size!

**Comment by sabrogden** [comment]
The sort issue has been fixed, https://ditto-cp.sourceforge.io/beta

**Comment by SanderBouwhuis** [comment]
> The sort issue has been fixed, https://ditto-cp.sourceforge.io/beta

Ok, sorting works now.

But, why is every entry in the list so many times?
![2022-02-10 10-39-50 1275x924 Delete_Clip_Data](https://user-images.githubusercontent.com/10495173/153380286-20d4f30a-a5ab-4ba7-8d9f-4d02544f7692.png)

**Comment by sabrogden** [comment]
Each clip is made up of multiple formats (text, image, rtf, ...).  This window lists each format associated with a clip.  This lets you delete the larger formats in each clip while keeping the other formats.
