### ISSUE TITLE
Please retain the title of the clip after editing it.

### ISSUE THREAD

**Issue by CaptainFrosty** [sabrogden/Ditto#252]
It's annoying to have to re-add the title every time I edit the clip.

**Comment by sabrogden** [comment]
On the clip editor screen there is a check box "Update clip description on save" on the bottom.  Uncheck that to leave the description/title the same.

**Comment by CaptainFrosty** [comment]
@sabrogden Oh, I see it there on the bottom....can't believe I missed that. My apologies.
