### ISSUE TITLE
【Feature Request】Is there a way to set a custom shortcut key for [Prohibit Auto Delete]?

### ISSUE THREAD

**Issue by MAKER555** [sabrogden/Ditto#254]
【Feature Request】Is there a way to set a custom shortcut key for [Prohibit Auto Delete]?

**Comment by sabrogden** [comment]
Sorry no plans to support this.

**Comment by az-pz** [comment]
You can set keyboard shortcut to open the context menu and use `<context-menu-shortcut>+Q+N` to set the item to Never Auto Delete. Similarly you can use `<context-menu-shortcut>+Q+A` make the item auto delete.


There's another workaround. You can set shortcut to move the clip to a group using shortcut. I am using default keyboard shortcuts to show how to do that.

1. Open ditto: Ctrt+`
2. Show the hierarchy of Groups in a treeview (Ctrl+G)
3. Right click on `No Sub Group` and create a new group named `Pinned`.
4. Right click on `Pinned` group and click on properties.
5. Set `Hot Key` (e.g. Ctrl+Shift+P ) and `Save/Move To Group` (e.g. Ctrl+P) and click ok. Don't change the `Move to Group` section. It should remain as `-No Grpup-`.
6. Ctrl+P will pin an item.
7. Ctrl+Shift+P will open the pinned items and Backspace will take you to all items.
