### ISSUE TITLE
Entry reappears after I delete it when I open Notepad++?

### ISSUE THREAD

**Issue by brskiiii** [sabrogden/Ditto#282]
Don't know if this is a bug or feature, when I delete an entry from Ditto, it appears again when I open Notepad++. 

How to reproduce: 1. have Ditto running and copy something to clipboard. 2. delete it from Ditto. 3. open Notepad++. 4. check Ditto and you will see that the data entry has reappeared. 

It is kind of annoying because I have certain data I copy to clipboard, and no longer need it, so I delete it from Ditto, but then later find it in Ditto forgetting that I had previously deleted it.

Any idea what's causing this to happen, whether it is a bug or feature, in Ditto or NPP++?

**Comment by garoto** [comment]
Sounds to me like a Notepad++ specific thing. Keep in mind that when you delete the most recent clipboard entry from Ditto's database, that won't erase the actual, current clipboard contents. I don't use Notepad++, so I can't really check, but I've never seen anything like this behavior with Ditto in the almost 20yrs using the program. Perhaps something to do with more recent, newer Windows versions (like 11).

**Comment by sabrogden** [comment]
I'm not seeing this issue.  Something has to be setting clipboard data when opening notepad++.  The only way Ditto adds entries is if it receives a clipboard change notification from windows.  Check your extensions in notepad++.

**Comment by brskiiii** [comment]
Ahh there it is. I had a plugin called MultiClipboard installed in NPP. Not sure how long that has been installed but it's probably been years. I removed it and everything seems to be fine now... I think and hope so. 

Dang that was so annoying it is such a relief. Thanks bros! :)
