### ISSUE TITLE
Pasting selection into Cygwin

### ISSUE THREAD

**Issue by andrewakl** [sabrogden/Ditto#29]
I'm using [Cygwin](https://www.cygwin.com) 

When i try to paste a selection, it looks like a Ctrl+V is sent, which doesn't paste the item into the Bash console of Cygwin.

I tried to change the keyboard shortcut as follows:
![image](https://user-images.githubusercontent.com/59714327/103071129-d57b8980-4577-11eb-8e18-ec1fe54ada07.png)
but that also sends CTRL+V

Is it possible to have Ditto use Shift+Insert to paste the selection instead of Ctrl+V  ?

**Comment by sabrogden** [comment]
https://github.com/sabrogden/Ditto/wiki/Custom-Key-Strokes

Double check that is the process name on your setup, in my testing it was mintty.exe


[HKEY_CURRENT_USER\SOFTWARE\Ditto\PasteStrings]
"mintty.exe"="+{INS}"

**Comment by andrewakl** [comment]
Thanks.  Adding that mintty.exe entry to the Windows Registry worked.
