### ISSUE TITLE
How to set Win+backquote as shortcut key to activate ditto

### ISSUE THREAD

**Issue by gepcel** [sabrogden/Ditto#290]
The default shortcut key to activate ditto is Ctrl + backquote. I used to change it to Win+backquote. But with the current version, I can't do that anymore. Did I misoperate something or something had changed?

**Comment by grehung** [comment]
我记得之前我也能，当前版本也不能了

**Comment by gepcel** [comment]
从微软应用商店下载的版本好像仍然可以。官网的不能。

**Comment by Young-Lord** [comment]
是管理员权限运行的吗？而且`Win`键本来就是内部使用的，不建议绑定给第三方应用

**Comment by gepcel** [comment]
I'm going to close this issue, since it no longer exists now. Maybe it wasn't an issue in the first place.
