### ISSUE TITLE
close ditto using command line

### ISSUE THREAD

**Issue by jflefebvre06** [sabrogden/Ditto#297]
Could you please add a way to close ditto using command line (terminate program) ?

**Comment by sabrogden** [comment]
taskkill /im ditto.exe /t /f

**Comment by jflefebvre06** [comment]
Thanks but this method not close ditto properly, icon into task bar still showed even if ditto not still running

**Comment by sabrogden** [comment]
The latest https://ditto-cp.sourceforge.io/beta now supports "Ditto.exe /Exit"

**Comment by jflefebvre06** [comment]
Thanks

**Comment by tgaletak** [comment]
> The latest https://ditto-cp.sourceforge.io/beta now supports "Ditto.exe /Exit"

Sorry, but it does not work for me with 03.24.238.00 64 bit on Win11. Actually none of command line options.
