### ISSUE TITLE
Delete by size

### ISSUE THREAD

**Issue by quammy** [sabrogden/Ditto#30]
Hi, 

_I hope it's ok to suggest here a feature request. Else, please let me know where is the right place._

Is it possible to add a deletion by DB size? Or maybe clip's size?

Besides, this is a GREEAT tool, one of my most used ones ;)

Thanks

**Comment by sabrogden** [comment]
Right click on the task bar icon - Delete Clip Data.  From here you can see the db size, each items size and delete as needed.

**Comment by quammy** [comment]
That's great! Not sure how I missed it so far...;)
Thanks.
