### ISSUE TITLE
[enhancement ] Keyboard shortcuts for individual clips

### ISSUE THREAD

**Issue by s-i-m-lem** [sabrogden/Ditto#307]
I am using Ditto as my secondary clipboard manager, where I store clips of text etcetera that I use more often, and some of my clips I use so often, that I would really welcome the possibility of adding special keyboard shortcuts to them.

**Comment by sabrogden** [comment]
Each clip can have a shortcut key set, this can be active only when Ditto is active or globally available.

![image](https://user-images.githubusercontent.com/16867884/179537562-98c2539e-73e8-4854-a7ce-9d21e8b88d5f.png)
