### ISSUE TITLE
Clips not showing on 4096x2160 resoultion

### ISSUE THREAD

**Issue by Mr-Orme** [sabrogden/Ditto#308]
![Ditto](https://user-images.githubusercontent.com/25017905/179360180-7c362874-e7ef-4540-a020-566434b92e2b.PNG)

I recently bought a 43" TV to use as a monitor if I set it at the max resolution of 4096x2160 you see the attached image with ctrl+`
I tried changing the font size in Ditto and the zoom setting in windows. Lowering the resolution to 3840x2160 does fix the issue, but then I have black bars on the side of the monitor.

**Comment by sabrogden** [comment]
What scaling factor are you using

![image](https://user-images.githubusercontent.com/16867884/180103353-d52b98e6-989f-4abe-8856-43bdafe652a2.png)

**Comment by Mr-Orme** [comment]
I've used both 200% and 300% to the same effect. I just now tried 100%.
Doing the same thing.

Sean Orme | Computer Science Instructor

University of Arkansas at Little Rock | EIT 576
(501) 916-5291 | ***@***.*** | http://ualr.edu/computerscience/
<http://ualr.edu>

**Comment by sabrogden** [comment]
Something else to try, go to the registry path, Computer\HKEY_CURRENT_USER\SOFTWARE\Ditto and delete all entries (yy x yy)_QuickPastCX/CY.  Then restart.

![image](https://user-images.githubusercontent.com/16867884/180113465-bbbd48d3-db2b-4941-8cc8-c4a2f92ce0e6.png)

**Comment by Mr-Orme** [comment]
No. I have been arrowing down however many times I think I need to to get
to the one I want.
Sean Orme | Computer Science Instructor

University of Arkansas at Little Rock | EIT 576
(501) 916-5291 | ***@***.*** | http://ualr.edu/computerscience/
<http://ualr.edu>

**Comment by Mr-Orme** [comment]
Deleting those registry keys did the trick...
Sean Orme | Computer Science Instructor

University of Arkansas at Little Rock | EIT 576
(501) 916-5291 | ***@***.*** | http://ualr.edu/computerscience/
<http://ualr.edu>
