### ISSUE TITLE
Find as type problem in beta 3.24.230

### ISSUE THREAD

**Issue by kesdoputr** [sabrogden/Ditto#314]
Hello, i try newest beta 3.24.230

And i found：

step1：I press hotkey to call ditto and type some words for find and enter for paste.
setp2：I call ditto and still see the previous find result in ditto window.

I need to press esc to show the normal ditto window.
But in previous beta 3.24.226, i can see normal ditto window in step2.

Is there some setting can let the behavior like previous version?
Thanks for your reply.

**Comment by sabrogden** [comment]
Should be fixed in the latest, https://ditto-cp.sourceforge.io/beta

**Comment by kesdoputr** [comment]
Thanks for your reply, fixed confirm.
