### ISSUE TITLE
Can Ditto copy a list of words and paste it in sequential order?

### ISSUE THREAD

**Issue by nazdra** [sabrogden/Ditto#32]
Hey there! i have a project right now that requires an incredible amount of copy and pasting lines of info and I was wondering if I could possibly use ditto to make it a little more efficient?

Ex:
Bob is
Ham is
Mark is

Copy that column in Excel and then paste it into say a word doc 

I.E 

ctrl v Bob is
Ctrl v Ham is
Ctrl v Mark is 

I found another clipboard manager that starts a “collection” but each item has to be copied manually and then the list itself can only be about 50 items long. Thank you so much for taking the time to read this and how you had a wonderful holiday!

**Comment by sabrogden** [comment]
You can always select multiple clips and paste them together, each clip will be on its own line.

**Comment by nazdra** [comment]
> You can always select multiple clips and paste them together, each clip will be on its own line.

Hey Sabrogden really appreciate the reply! I apologize for not being more specific, people on other threads haven't totally understood what I mean and I wish I had a better way to elaborate. 

But I'm actually pasting into a charting platform and have a list of futures that need to be in there own chart.

For example 

NG   F21:NGG21
NG F21:NGH21
NG F21:NGJ21
NG F21:NGK21
NG F21:NGM21

I want to copy this entire list in excel then paste each individual item into a separate chart or window

**Comment by sabrogden** [comment]
Ditto can combine multiple copies into a single paste but it can't take a single large copy and break them into individual pastes.

**Comment by sybaris** [comment]
Hi,

I have exactly the same need.
I would like to take a multiline text (1 line = 1 clip), and to import to ditto to make as many clip as lines.

Regards
Sybaris
