### ISSUE TITLE
I am regularly seeing a text value previously in clipboard not being in the paste window of Ditto history

### ISSUE THREAD

**Issue by rluiten** [sabrogden/Ditto#323]
I have a simple process that lets me copy a `url` from a web page and then I copy some manually `selected text` in the page.
I then go back to VSCode and execute a text snippet in VSCode which using snippet template creates a entry in a data structure and pastes in the `selected text` and leaves the cursor on a field for the url.
I then activate ditto to manually paste in the copied url.

On average 1 in 10 times the copied title in the clipboard is not visible in ditto.
Sometimes this can happen 3 times in row on successive pages.
This has been a problem for me for many weeks now.
I see the `url` but the `selected text` which when working follows the `url` in history order is not there when it fails.

I have recently tried switching to using windows 10 built in multi clipboard and in the last week this has not missed a single clip board value.

I like ditto but it's become unusable.
Is there something I can capture about this process to possible assist in fixing this problem?
I am on a fully patched window 10 21H2 PC.

**Comment by sabrogden** [comment]
How fast are you copying "selected text" after the url, Really fast?  Some settings to play around with, options - general - advanced.

![image](https://user-images.githubusercontent.com/16867884/185279217-a1353291-2484-41f1-8a13-e15276ccc9ab.png)

You can also enable logging, https://github.com/sabrogden/Ditto/wiki/Debug-Logging, send the logging file back noting the exact time of the issue and we can take a look

**Comment by rluiten** [comment]
I plan to look at those options and the debug stuff soon.

I've expanded the description of the sequence of events
- alt-d go to url of browser
- copy1 (ctrl-c)
  -  200msec  or higher from executing "go to address bar shortcut" 
  -  this copy1 is always visible in history
- mouse drag select and copy2 (ctrl-c)
  - Possible to get it done in 1 second usually over 2 seconds plus. I am not hurrying and not that fast.
  - This is the one that is not visible in history often enough for it to bug me below.
- I go to VSCode type template abbreviation in
- expand template
  - it always pastes copy2 correctly (just current value of clipboard is used in template)
- paste copy1 from ditto
  -  my muscle memory wants to go to 2nd entry and paste but with cop2 being lost often enough copy1 is them first in history

**Comment by sabrogden** [comment]
try changing those values to 150 and 25.  Or send or look into debug, look for the logging message "Clip copy to fast difference from last copy"

**Comment by rluiten** [comment]
I have been using your suggested settings for a day so, and have not had an occurrence of losing something in the clipboard as above. This looks like its resolve things for me.
Thankyou very much.
