### ISSUE TITLE
Configure to listen on loopback interface only, not wider network

### ISSUE THREAD

**Issue by epa** [sabrogden/Ditto#33]
For security reasons I'd like to configure Ditto to send and receive only on the local loopback interface 127.0.0.1, and not open an externally visible port 23443.  Could there be a configuration option for that?

**Comment by sabrogden** [comment]
https://ci.appveyor.com/project/scottbrogden/ditto/build/artifacts

options - general - advanced - "Network Server Bind IP (default: *)  Set this 127.0.0.1, requires a restart, then Ditto will only accept connections on that IP address.  Normally this is set to accept connections from any network card ip address.

![image](https://user-images.githubusercontent.com/16867884/103469709-60e9dd00-4d25-11eb-80a4-456ebc2a2abf.png)

**Comment by epa** [comment]
Thank you.
