### ISSUE TITLE
Ditto doesn't appear in Tray or respond to hotkeys

### ISSUE THREAD

**Issue by cool-RR** [sabrogden/Ditto#342]
I've been a happy user of Ditto for the last decade. Recently I reinstalled Windows 7 on one of my computers. I installed Ditto, and it worked for a bit, but now I see a weird behavior where it doesn't respond to the hotkey (Start-V). After some trial-and-error, I found that when I launch Ditto, it sometimes doesn't put its icon in the Tray, and doesn't respond to the hotkey, even though Process Explorer confirms that ditto.exe is running. 

Things I tried:
1. Restarting Ditto.
2. Restarting the computer.
3. Uninstalling and reinstalling Ditto. (Factory settings.)
4. Looking for error logs in "C:\Users\Administrator\AppData\Roaming\Ditto", there are no logs there.

What can I do to diagnose and fix this problem?

**Comment by sabrogden** [comment]
1. Verify the hot key is registered  right click on the task tray or ... - Global Hot Keys.  Verify that DittoHotKey is registered.  
2. Try changing the hot key to something else.
3. Enable logging in options - general - advanced - "Write debug to file".  This will write debug to "C:\Users\Administrator\AppData\Roaming\Ditto" post back or see if you see any errors in there.

![image](https://user-images.githubusercontent.com/16867884/192904090-6320106f-f72a-452d-b34d-45a6298b45ee.png)
![image](https://user-images.githubusercontent.com/16867884/192904218-a4a8e2b8-3ba2-4e1c-971b-ee4b36cd6048.png)

**Comment by cool-RR** [comment]
I can't do any of these things because the Ditto tray icon doesn't even show up.

**Comment by sabrogden** [comment]
try running, Ditto.exe /Open

https://github.com/sabrogden/Ditto/wiki/Command-Line-Options

**Comment by cool-RR** [comment]
Huh, now I can't reproduce the problem :) Ditto is working fine. I'll close this issue, and if it happens again I'll try your line and reopen. Thanks for your help.
