### ISSUE TITLE
Windows On ARM（ARM64） Support

### ISSUE THREAD

**Issue by slzKud** [sabrogden/Ditto#362]
Hello! I recently purchased a Windows Dev Kit 2023 running the ARM64 version of Windows 11. Because Ditto is my commonly used software, I try to compile the source code and run it natively. After a few changes, Ditto is running fine.Ready to initiate Pull Requests.
![图片](https://user-images.githubusercontent.com/23147878/198924852-58ac53f1-fefe-4f3b-a95a-ca6ac505aa61.png)
But I have a problem, the zlib used in the project is zlib-msvc installed from Nuget, and there is no arm64 version of zlib. So when I adapt, I will remove the zlib obtained from nuget and use the arm64 version of zlib compiled by myself.
So I want to confirm how this situation should be handled. My personal recommendation is to use a package manager such as vcpkg, or change the source/readme/action to use the independently compiled zlib library. I want to ask your opinion to see how you treat and deal with it, thank you!

**Comment by jglathe** [comment]
Oops did the same apparently. See merge #376 . Made a (static) zlib from the original source. Anyway, next up would be to make it a nuget package and publish it. The dll also gets built, didn‘t want to mess with this before ditto was running natively on ARM64 Windows. Please see jglathe/zlib for the current state of work.

**Comment by slzKud** [comment]
Nice! Thank you! I will close this issue.
