### ISSUE TITLE
Selecting multiple clips and moving up/down breaks selection

### ISSUE THREAD

**Issue by KDASthenerd** [sabrogden/Ditto#398]
Say I have 10 clips, but they're in the "wrong" order: 1, 2, 3, 6, 7, 8, 4, 5, 9, 10
I'd like to put them in order so that I can properly use the hotkeys for last 10 clips more easily.
I also have shortcuts for the "move up" and "move down" commands.

One of the fastest ways to solve this would be to select clips 4 and 5, then use the "move up" shortcut three times.
Problem is: after the first "move up", the selection is undone, and it goes back to having only one clip selected.

Curiously, it seems to work properly as long as the selected clips are in a very specific order.
Upon moving clip 4 so that it's below 5, it is now possible to select both and move them all at once. This should be possible regardless of the order of the selected clips.

Another way would be to select 6, 7, and 8 and move them down two times.
This would be even more of a nuisance, since there is only one chance in six that the three clips are in the specific order needed for it to work properly.

**Comment by sabrogden** [comment]
Can you verify this is fixed in the latest, https://ditto-cp.sourceforge.io/beta/

**Comment by KDASthenerd** [comment]
Verified and it's working.

**Comment by KDASthenerd** [comment]
Verified and it's working.
