### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by daliovic** [sabrogden/Ditto#4]
Ditto is the best clip manager I have ever used, especially for for images and graphics support.
I install it on every computer I use or fix. 
It would be a great idea for us to have our clip history somewhere in the cloud and better yet a mobile app.
The good thing is that it doesn't seem too hard to make this and we will be really grateful

**Comment by mohammadTahreem** [comment]
I have recently switched to a macbook and this is the only basic productivity tool that I miss the most. There is nothing out there in MAC that comes close to Ditto for windows(Including the paid ones). Can you please create one for mac.

**Comment by sabrogden** [comment]
I would love to be able to do all that, cloud, mobile, and mac but no plans for any of these.

**Comment by McJayFeng** [comment]
> I would love to be able to do all that, cloud, mobile, and mac but no plans for any of these.

Do you have any plans for these now?
