### ISSUE TITLE
Single click / Double click

### ISSUE THREAD

**Issue by tom-ot** [sabrogden/Ditto#5]
To select and use a copied item, I have to double-click it from within the list.
Any way to only single-click?

**Comment by FutureLearnSole** [comment]
Is the copied item re-used frequently? Might want to sticky that...
  Else, you might want to type in some letters to match the copied item and hit `Enter`

**Comment by KOGI** [comment]
I second this request to at least have a config/option for single-click select of the item I want to paste from the QuickPaste window. I'm coming to Ditto from another clipboard manager and am struggling to break the single-click expectation in my mind!
