### ISSUE TITLE
Double click auto pastes when it should not

### ISSUE THREAD

**Issue by darthglader** [sabrogden/Ditto#501]
Double clicking on an entry should load the entry into the clipboard. The user can then paste it where they want.

Currenltly the double clicked item is dumped where the cursor is.  This is not cool.

**Comment by amirasyraf** [comment]
This behaviour can be modified.

Options -> General -> Advanced -> `Paste clip in active window after selection`

**Comment by amirasyraf** [comment]
This behaviour can be modified.

Options -> General -> Advanced -> `Paste clip in active window after selection` = `False`

**Comment by sabrogden** [comment]
Or press ctrl-c to only copy the clip and not paste.

**Comment by darthglader** [comment]
Brilliant thanks.  I think this option should not be buried so far in the options though, and personally i think it should default to False :-)
