### ISSUE TITLE
how to exclude images and other larger file copy?

### ISSUE THREAD

**Issue by dinaau** [sabrogden/Ditto#509]
just want Ditto to save plaint text only 

having used for couple months now and the database is 2.7GB too large...

**Comment by tuwulin365** [comment]
trayicon right menu - delete clip data

**Comment by garoto** [comment]
![screenshot-0809-08-07-2023](https://github.com/sabrogden/Ditto/assets/11768175/25130a91-4cf3-4b5a-a24c-83aaf9f3d991)
