### ISSUE TITLE
Hi Gang, I am very new to computers and I am looking for a program that allows you to copy and paste content on two different hot keys (I think that is what you call them) I know I can copy with ctrl C and paste with ctrl V but with Ditto can you copy and paste using other keys and not loosing the first copy and paste content?  I don't know if I am explaining this well enough but if I am not please let me know.  Any help you can give me would be most appreciated.  Donna

### ISSUE THREAD

**Issue by dspkoala** [sabrogden/Ditto#51]
Hi Gang, I am very new to computers and I am looking for a program that allows you to copy and paste content on two different hot keys (I think that is what you call them) I know I can copy with ctrl C and paste with ctrl V but with Ditto can you copy and paste using other keys and not loosing the first copy and paste content?  I don't know if I am explaining this well enough but if I am not please let me know.  Is Ditto the progam that I need and will do more then one copy and paste? Any help you can give me would be most appreciated.  Donna

**Comment by sabrogden** [comment]
https://github.com/sabrogden/Ditto/wiki/Copy-Buffers

**Comment by dspkoala** [comment]
Hi Team,

I installed Ditto and now it will not work.  When I click on the hot keys
or the icon it keeps wanting me to make changes to my computer which I did,
but it will not go any further.  What should I do?  I know this sounds
silly but I can not figure this out after trying for 2 hours.  Please help
me!

Warmest Regards!
*Tara*
ShirtsToPrint.com
5615 Crawford Street
New Orleans, LA   70123
504-400-3849
shirtstoprint@gmail.com

*Like us on Facebook  <https://www.facebook.com/shirtstoprint/>*
