### ISSUE TITLE
This program changed my life and I'm so glad you maintain it

### ISSUE THREAD

**Issue by hwayne** [sabrogden/Ditto#510]
That is all

**Comment by shodanx2** [comment]
I agree, in computer terms Ditto feels like having an extra arm.

Once you're used to it, it is so obvious. How can all computer not have this software, it is absolutely essential. 

A computer without DItto is like a mouse without a right-click, or a computer with just one monitor. 

I tell my computer friends and they say "oh I'll just put extra stuff in notepad or something", they just don't get it.

**Comment by garoto** [comment]
> or a computer with just one monitor [...]

I feel attacked.
