### ISSUE TITLE
The reaction of a third-party program (BattleEye anticheat) to Ditto.

### ISSUE THREAD

**Issue by zombieserv** [sabrogden/Ditto#513]
Hi all.
I'm sorry to post here, but my request is really important to me and directly related to Ditto.
I need advice from a developer (or anyone who might be able to help).
I have this problem: I got banned from PUBG on Steam.
Game block, not a VAC ban, but a shameful red sign hangs in my profile.

Actually, what does Ditto have to do with it - when starting the game, their in-game anti-cheat (BattleEye) pointed to Ditto.exe as a suspicious program.
I don't know why, maybe because it runs on top of all windows - BattleEye thought I was breaking into the game's memory.. I don't know.
The bottom line is that I closed Ditto, restarted the game - everything was fine, played 2 times, exited.
The next day I got a message: the game developer has blocked you permanently in PUBG: BATTLEGROUNDS.

This was in 2018, and now I've been trying to get an explanation for a little over 5 years.
Their support does not go help me, they say: "we are sorry that this happened, but the block was give correctly and cannot be removed."
I say - well, do not remove the blocking, just tell me what it is reason? To which I hear: "We can not provide any details."

I did not break anything, did not use cheats and macros, did not climb into the game's memory.
My only lead that I'm trying to do justice to is BattleEye's swearing at Ditto.
And to my titanic regret, I did not think to screen it. But the message about Ditto.exe was displayed inside the console "BattleEye Launcher".

Maybe a developer or one of the contributors will be able to tell me what to do?
In the sense that maybe you can explain the technical aspect - how could BattleEye react to Ditto?
Have any Ditto users playing PUBG encountered a similar problem?
I despaired, I don't know how to prove that I didn't do anything wrong.

Thanks in advance to everyone, I will be glad for any answer, any advice or any help.

**Comment by sabrogden** [comment]
Sorry to here this but I can't help you here, Ditto monitors the clipboard for changes and monitors the active window for what window to activate on paste (both through windows sdk messages).  Don't believe these should affect your game.

**Comment by Van-Dame** [comment]
I can personally attest to the fact that Ditto never triggers a flag in any of the anti-cheat programs. I have played games with almost all of the Anti-Cheat (VAC, EAC, Battleye, etc.) with not **a single one** triggering any sort of flag. E.g. One of the biggest names with Battleye AC that I play almost every single day with Ditto always running in background:

![image](https://github.com/sabrogden/Ditto/assets/482549/31d9cb31-e0c2-4a76-a0c6-8562dff177b9)

**Comment by zombieserv** [comment]
> Sorry to here this but I can't help you here, Ditto monitors the clipboard for changes and monitors the active window for what window to activate on paste (both through windows sdk messages). Don't believe these should affect your game.

I do not think that Ditto could somehow affect the game, but the fact remains that something did not like by BattleEye, and "Ditto.exe" appeared there. Maybe something happened in conjunction with the antivirus .. I don’t know.
In any case, thank you very much for your feedback, for the answer and for trying to help.
I will continue to contact PUBG support.

**Comment by zombieserv** [comment]
> I can personally attest to the fact that Ditto never triggers a flag in any of the anti-cheat programs. I have played games with almost all of the Anti-Cheat (VAC, EAC, Battleye, etc.) with not **a single one** triggering any sort of flag. E.g. One of the biggest names with Battleye AC that I play almost every single day with Ditto always running in background:
> 
> ![image](https://user-images.githubusercontent.com/482549/255395427-31d9cb31-e0c2-4a76-a0c6-8562dff177b9.png)

Yes, I also never had any problems with anything after that incident.
I will try to get justice. Thank you very much for the you answer.
