### ISSUE TITLE
Scripting: paste current date

### ISSUE THREAD

**Issue by sharchun** [sabrogden/Ditto#520]
I would love a function to paste the current date (even better, to customize the format of it e.g. "August 9, 2023" or "09/08/2023").  I looked into the scripting capability that is included with Ditto but unfortunately I couldn't figure out how to access any date functions using Chaiscript.  I wasn't able to find any documentation on this and not sure whether it's possible to do in Ditto.  Anybody know how?

**Comment by PzaThief** [comment]
I'm late.
You can use FormatCurrentTime function in chain script.
parameter is format what you want and return is string.
simply used like `var csText = FormatCurrentTime("[%Y-%m-%d %H:%M:%S - ");`
the function is just wrapper of CTime.format, So see [format code](https://learn.microsoft.com/ko-kr/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-170#generic-text-routine-mappings) if you want change the format
happy new year~

**Comment by sharchun** [comment]
Not too late!  It works and is exactly what I wanted 😊 Thank you!!

**Comment by Chealer** [comment]
I do not understand very well, but I **assume** that @PzaThief is referring to an On Paste [Script](https://github.com/sabrogden/Ditto/wiki/Scripting) and that by "chain script", he means ChaiScript.

<details>
  <summary>License</summary>
This comment and any other I might add to this ticket is offered under the terms of CC0 1.0.
</details>
