### ISSUE TITLE
[Solved] Is it possible to give entries a name/description?

### ISSUE THREAD

**Issue by SanderBouwhuis** [sabrogden/Ditto#527]
I often have things like complex queries I write for customers, and then want to keep them for a long time in order to be able to look back at what I did to help them in the past.
I choose to 'never auto delete' the entry, but I would also like to give it a name/description so that I can find it back. Currently, I would have to search for specific texts which are in the entry itself, but it would help enormously if I could also search in a description (which is NOT part of the copy'n'pasted entry).

Is this currently possible?
If yes, how? If no, can this please be added?

**Comment by garoto** [comment]
<kbd>alt</kbd>+<kbd>enter</kbd>, then edit the text field named "Item Title".
