### ISSUE TITLE
Images preview too small on high DPI

### ISSUE THREAD

**Issue by dotnetwise** [sabrogden/Ditto#53]
I have big monitors and I use 150% DPI and the preview images on DITTO quick-paste list show very very small.
Is there a way you could add support for configuring image size preview?

**Comment by scottbrogden-iheartmedia** [comment]
What version are you using?  Make sure you are on the latest, https://ditto-cp.sourceforge.io/.  Is the text preview also small?

**Comment by dotnetwise** [comment]
03.23.124.00
I guess the latest.
No, the text is fine - just I would like to be able to choose the height of the picture.
I don't mind if they will be big and I have to scroll a lot.
Also on the text, _CF_DIB_ would be nice to also add the date 
**CF_DIB 2020 Jan 22, 10:20:23**
This would help you to search/filter/loop through all the images copied on a particular day. 
Much more usability!

I guess this could be easily implemented - but will it?

Thank you!
![image](https://user-images.githubusercontent.com/485535/107095371-f38c0900-6808-11eb-8216-79078e10e8bb.png)

**Comment by scottbrogden-iheartmedia** [comment]
The inline-image preview will be small, press F3 to view a larger image. This is still a zoomed image, click on the image in the F3 viewer to see the full-size image.  Control-mouse wheel to zoom in/out of the image.  With the F3 viewer open you can press up/down or n/p to view the next or previous item in the list.

The tooltip or the F3 viewer will show you when the clip was added.

**Comment by dotnetwise** [comment]
The F3 does nothing on an image clip line (CF_DIB).
However my idea that the CF_DIB text also contains the date was to be able to quickly search through the clips of a certain date that I may remember and exclude everything else that doesn't match, so better than a tooltip.

In my case that tooltip also is not displayed.
Here are my shortcuts configured - do I miss anything?
![image](https://user-images.githubusercontent.com/485535/107103270-6606e400-681d-11eb-812a-ccf8606ce778.png)

**Comment by scottbrogden-iheartmedia** [comment]
![image](https://user-images.githubusercontent.com/74422469/107113046-7917b500-6819-11eb-8362-35feea816aef.png)

**Comment by dotnetwise** [comment]
View Full description works, but it is still not searchable
