### ISSUE TITLE
Feature Request: API for opening Ditto Editor with specific entry ID

### ISSUE THREAD

**Issue by ronstudy1** [sabrogden/Ditto#54]
Ditto's "Quick Paste" GUI is useful for most cases. However sometimes I feel the need to bypass its opening and run some commands directly

e.g. I have a set of  entries which i edit very frequently. It could be useful to open Ditto Editor for specific entry using some API 

With AutoHotkey it's possible to create a hotkey/hotstring that sends specific entry ID to ditto using "[PostMessage](https://www.autohotkey.com/docs/commands/PostMessage.htm)". But Ditto has to support such Message.
It could be great if it's possible to have something similar to the following AutoHotkey function:
```
ditto_open_editor(entry_id){
	lEntry_id:=entry_id & 0xffff
	wEntry_id:=entry_id >> 32
	PostMessage, MESSAGES_DITTO_EDIT_ENTRY, wEntry_id, lEntry_id, , ahk_exe ditto.exe
}
```
Opening editor is just one example, but similar messages can be added for pasting an entry or opening the "Properties" dialog of an entry

Ditto is already a great tool. Having the ability to control it from 3rd-party applications can make it even more useful

Thanks!

**Comment by sabrogden** [comment]
Build is on it's way, https://ditto-cp.sourceforge.io/beta/

https://github.com/sabrogden/Ditto/wiki/Command-Line-Options


Ditto.exe /Edit:(clip id)
- Opens the clip editor for a clip by the id, clip id can be found in the window title of the clip properties
- You can also post a message to Ditto window ::PostMessage(hWnd, 1258, (clip id), 0)
- (as of version 3.24.180.0)

Ditto.exe /Paste:(clip id)
- Pastes the clip by the id, clip id can be found in the window title of the clip properties
- You can also post a message to Ditto window ::PostMessage(hWnd, 1257, (clip id), 0)
- (as of version 3.24.180.0)

**Comment by ronstudy1** [comment]
Wow, that's great! I've dreamed of this feature for so long
Thanks! really appreciate it
