### ISSUE TITLE
What is the difference in a on copy and on paste script?

### ISSUE THREAD

**Issue by imthenachoman** [sabrogden/Ditto#546]
I'm not able to figure out when you use on copy vs on paste?

**Comment by garoto** [comment]
I figure one set of scripts act on when a copy is registered by the program and the other when a paste is called from within the same program? I mean, it says right there at the tin.

**Comment by imthenachoman** [comment]
But what’s would you do to a clip on copy? You’d alter clips on paste, right? Like I’m not understanding use cases for on copy. What am I missing?

**Comment by garoto** [comment]
I see yeah, copy scripts can be very niche indeed. Check the Wiki for some use cases: https://github.com/sabrogden/Ditto/wiki/Scripting

**Comment by sabrogden** [comment]
On copy scripts let you modify the data before it comes into Ditto, set as sticky, move to a group, remove formats.

**Comment by imthenachoman** [comment]
> I see yeah, copy scripts can be very niche indeed. Check the Wiki for some use cases: https://github.com/sabrogden/Ditto/wiki/Scripting

I read that but it didn't help make sense of what I was asking.

> On copy scripts let you modify the data before it comes into Ditto, set as sticky, move to a group, remove formats.

Now I get it. Thanks!
