### ISSUE TITLE
Is English.xml updated?

### ISSUE THREAD

**Issue by StoyanDimitrov** [sabrogden/Ditto#549]
I'm translating the application and there are several strings that differ across existing translations and English.xml. One of the examples is the missing (in English.xml) string `Delete All Non Used Clips`. The other one is `"Order" ID = "-1"` in some translations and `"Sort" ID = "-1"` in other.

**Comment by sabrogden** [comment]
I've updated the English file with the missing translations that i could find. 

https://github.com/sabrogden/Ditto/blob/master/Debug/Language/English.xml
https://github.com/sabrogden/Ditto/commit/60ce2ad785c42764dd592c7fa7d0a08e196380d3
https://ditto-cp.sourceforge.io/beta/

**Comment by StoyanDimitrov** [comment]
Thank you!
