### ISSUE TITLE
Feature Request - Option to keep window open

### ISSUE THREAD

**Issue by vertigo220** [sabrogden/Ditto#55]
I'd like to be able to leave the Ditto window open on the edge of the screen, but currently there's no option to do so. When clicking off of it, instead of it closing, I'd prefer if it would just collapse to show the caption. After all, it has that capability, but it doesn't seem to have any use currently.

**Comment by ditzyalbatross** [comment]
![Untitled](https://user-images.githubusercontent.com/76421749/106613217-02f62280-657b-11eb-96ec-3ddee2cf2601.png)

**Comment by vertigo220** [comment]
Thanks. That's exactly what I wanted, just a very confusingly labeled option.

**Comment by vertigo220** [comment]
Closing this issue in favor of a new one.

**Comment by Chealer** [comment]
@vertigo220 wrote:
> I'd like to be able to leave the Ditto window open on the edge of the screen, but currently there's no option to do so. When clicking off of it, instead of it closing, I'd prefer if it would just collapse to show the caption.

To obtain that, you need to [enable _Always on top_](https://github.com/sabrogden/Ditto/issues/692#issuecomment-3688466416) and _Auto Roll-up_.

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>
