### ISSUE TITLE
question about scripting

### ISSUE THREAD

**Issue by giturfreakon** [sabrogden/Ditto#554]
i tried example 6...
```
clip.AsciiTextReplaceRegex("[\\\\/:\"*?<>|]+", "_");

return false
```
...with the string `Hello?`

i tried it as on copy script.

what's copied:
`Hello_`

what's pasted (ctrl + v):
`Hello?`

what's pasted (ctrl + num 1):
`Hello_`

then i tried it as on paste script.

what's copied:
`Hello?`

what's pasted (ctrl + v):
`Hello?`

what's pasted (special paste):
`Hello_`

is this how it's supposed to work? can't i just press `ctrl + v` to get the desired result? (but i guess i can see how it could cause problems.)

**Comment by sabrogden** [comment]
Yes that is how it's supposed to work.  On copy scripts modify the data before placing it in Ditto and on paste scripts modify the data when doing a special paste with that script.

on copy script

So you copied Hello?  Ditto modified it to Hello_ when importing it into Ditto so when pasting from Ditto you have Hello_.  Ditto doesn't modify the current clipboard so it still has Hello when pasting from ctrl-v (without pasting from Ditto first).

on paste script

You copied Hello?, it will paste Hello? unless you do a special paste, then that will convert it to Hello_

**Comment by giturfreakon** [comment]
ok. that's helpful. thank you!
