### ISSUE TITLE
WhiteSpace char display as '?'

### ISSUE THREAD

**Issue by carldats** [sabrogden/Ditto#564]
![image](https://github.com/sabrogden/Ditto/assets/25075365/7be5b151-83e7-4e66-a731-8d0f757962e0)

**Comment by sabrogden** [comment]
What font are you using, Ditto trims white space at the start of each line and replaces it with 

`text += "» "`

Must not understand that character.

**Comment by tuwulin365** [comment]
It is not standard ascii.

**Comment by tuwulin365** [comment]
change source file to utf8, and then

text += L"» "

**Comment by sabrogden** [comment]
Please try the latest, see how this does for you, https://ditto-cp.sourceforge.io/beta/
