### ISSUE TITLE
Portable zip

### ISSUE THREAD

**Issue by romanoh** [sabrogden/Ditto#566]
Is it me or the [DittoPortable_64bit_3_24_246_0.zip](https://github.com/sabrogden/Ditto/releases/download/3.24.246.0/DittoPortable_64bit_3_24_246_0.zip) is empty?

**Comment by havrlisan** [comment]
> Is it me or the [DittoPortable_64bit_3_24_246_0.zip](https://github.com/sabrogden/Ditto/releases/download/3.24.246.0/DittoPortable_64bit_3_24_246_0.zip) is empty?

It is you. Downloaded through your link, zip file of size 4,69MB, with everything inside.

**Comment by romanoh** [comment]
thank you
