### ISSUE TITLE
Reposition Quick Paste Window

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [sabrogden/Ditto#567]
When LEFT CLICK to bring up Quick Paste Window, the window opens up CENTER SCREEN.

It used to open on the RIGHT side just above the DITTO icon. I drag it back over there and the next time it opens then it is center screen again.

How do I get it to remain on the right side above it's icon? Thank you.

**Comment by sabrogden** [comment]
You can set the startup position in options - general

- Caret (at the current typing position, if we can't find that position it's centered over the current window)
- Cursor (at the mouse cursor)
- Previous Position (will open up at the same location each time) Sounds like this is the one you need.

![image](https://github.com/sabrogden/Ditto/assets/16867884/1435f4bd-4263-49da-bc71-30160e9efef3)

**Comment by JazzyJazzjazzy** [comment]
Thank you for your kind reply. YES, that is just what I needed. Peace!
