### ISSUE TITLE
Prevent image from copying with text when using OneNote

### ISSUE THREAD

**Issue by kramttocs** [sabrogden/Ditto#583]
Text copied from OneNote looks to come in as html and then when I paste it into a rich text editor it adds the text along with an image of the text. Would like an option to just copy text so I don't have to remember to 'paste as text only'

**Comment by PzaThief** [comment]
How about use text only paste hotkey? you can set the hotkey in keyboard shortcuts.
Or, do you want a option to change Ctrl+V to paste as text only?

**Comment by kramttocs** [comment]
I am really not sure the best solution.
The problem with the text only hotkey is that it requires a person to know when it's needed. When copying only text from OneNote I wouldn't naturally think I'd need to use the text only paste option.

I also don't know that making the default paste as Text Only would be the right move as I don't really know how much that would impact.

**Comment by kramttocs** [comment]
It's just odd what it's doing. I am copying from OneNote into Jira and it pastes the text fine but at the bottom it adds a screenshot of the text.

**Comment by PzaThief** [comment]
I think we need to look conflict point between copy part and paste part.
First copy part application need to make proper types clip.
and Paste part application need to accept proper type of clip.

In OneNote copy action makes clip to have multiple types such as text, rich text, image(CF_DIB), etc. (you can find it clip detail, personally I don't know how much valuable image format from OneNote's text content)

So some app like PowerPoint makes choice list to user can select format of pasted content. (Nice compatibility for Office things)

But, Jira seems to have an issue with this point.
[Issue](https://jira.atlassian.com/browse/JRASERVER-60999), [community ask](https://community.atlassian.com/t5/Jira-Content-Archive-questions/Paste-Text-Problems-from-OneNote-to-Jira/qaq-p/2376683)
Jira probably doesn't want the image format to be found in the text content.
But there is image format in clipboard.

Thus, as you can see OneNote and Jira can not be a sweet couple.

In this situation I just recommend to use text only paste for a while before OneNote or Jira fixed this problem.

**Comment by PzaThief** [comment]
Well, while maybe i'm late for make a noise, I think I can make you more happy(maybe...?).
I found Office things common behavior about images.
Excel, PowerPoint and OneNote makes image formats and texts in tandem in case of text content copy.
But, many times user want to not taking images with text content.
So I can make an advanced option to ignore image when it detects that the original source is text content.
I think it will be listing option of the process names like "Excel.exe; PowerPoint.exe".
how do you think about this option idea? Is it worth the work?
btw, happy new year~

**Comment by kramttocs** [comment]
Happy New Year to you as well!
That would be fantastic!
