### ISSUE TITLE
Write notes within a copied item

### ISSUE THREAD

**Issue by tom-ot** [sabrogden/Ditto#6]
Is there any way to write notes about a copied item?
I am constantly copying product SKUs, and would love to be able to write what product the SKU refers to, such as "Red water bottle", "small water bottle". This would help me know which SKU to paste.

Thanks!

**Comment by FutureLearnSole** [comment]
Ditto this,
  select copied item > `Alt` + `Enter` > write in `Item Title:` field > Hit `OK`

    Any luck?

**Comment by tom-ot** [comment]
Yay!!!!! It's so cool! Thanks!!!

**Comment by sabrogden** [comment]
Thanks, FutureLearnSole, The title is what is shown in the UI and what is searched for, changing this doesn't change what is actually pasted.
