### ISSUE TITLE
Options to Keep Popup Open and optionally Always on Top

### ISSUE THREAD

**Issue by vbmark** [sabrogden/Ditto#602]
I don't see these options so forgive me if they already exist.

It would be great if there were two toggle options:

1. Keep popup open even after selecting an item
2. Keep popup on top of other windows

Of course number 2 would only be available if 1 is enabled.

Thank you.

**Comment by garoto** [comment]
Just double-click Ditto's titlebar thingy to make it alway-on-top:



https://github.com/sabrogden/Ditto/assets/11768175/b0b5ca1d-60af-48ef-8e94-ef27b6fae36d

**Comment by vbmark** [comment]
Perfect!  Thank you.

**Comment by Chealer** [comment]
@vbmark: Ditto always does #2. As for #1, it has long had an _Always on top_ option, and as reported in ticket #56, its name is misleading; it does not control #2, but rather #1.

So, if you want both, you just have to [enable that option](https://github.com/sabrogden/Ditto/issues/692#issuecomment-3688466416).

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>
