### ISSUE TITLE
How to export and import Ditto settings?

### ISSUE THREAD

**Issue by deadlydog** [sabrogden/Ditto#62]
Hey Scott, first off I want to thank you for producing some an awesome piece of software. Ditto is always one of the first things I install whenever I setup Windows :) 

That said, I often customize the Ditto settings quite a bit, and always having to manually reapply my customizations is a bit tedious. Is there a way to export and import just the Ditto settings? I know there’s the Backup and Restore Database commands, but that file grows as more data gets stored in the clipboard history, and is several hundred MBs. I’m curious how I can backup my Ditto settings before formatting my PC, and then restore them after reinstalling Ditto. I’m using the 64-bit Windows installer exe (e.g. DittoSetup_64bit_3_23_124_0.exe).

I searched [the wiki](https://github.com/sabrogden/Ditto/wiki) and GitHub issues, but could not find the answer to this.

Thanks so much.

**Comment by garoto** [comment]
From a cmd.exe window:

`reg export HKEY_CURRENT_USER\Software\Ditto DittoConf.reg`

**Comment by jay-ramani** [comment]
> From a cmd.exe window:
> 
> `reg export HKEY_CURRENT_USER\Software\Ditto DittoConf.reg`

Thank you.

Would be great if we had an option built into Ditto to export and import.
