### ISSUE TITLE
[Feature Request] Enhance group display

### ISSUE THREAD

**Issue by GAEREL** [sabrogden/Ditto#620]
Hi. 

First of all thanks for your job. I enjoy this utility.

Is it possible to add a small feature ?
I use groups to organize clips and I would like to return to the main group anytime the UI is open, not on the last used group.

Thanks for your help

**Comment by sabrogden** [comment]
Try setting "Revert to top level group on close" in options - general - advanced - "Revert to top level group on close" = true

![image](https://github.com/sabrogden/Ditto/assets/16867884/19310f58-5ad9-4c00-88b1-c82d9eb9945a)

**Comment by GAEREL** [comment]
Thanks a lot ! 
Problem solved.
