### ISSUE TITLE
'Options... Advanced... Disable Friends' does not work

### ISSUE THREAD

**Issue by dcog989** [sabrogden/Ditto#637]
1. set Options... Advanced... Disable Friends to True ... OK, OK
2. open Options... Advanced again - Disable Friends is set to False

Setting HKEY_CURRENT_USER\Software\Ditto\AllowFriends to 0 works.

v03.24.298 64-bit on Windows 11 (beta).

**Comment by sabrogden** [comment]
Fixed in the latest, thanks for reporting, https://github.com/sabrogden/Ditto/releases/tag/nightly

**Comment by dcog989** [comment]
Confirmed fixed. Thank you!
