### ISSUE TITLE
Ditto don't launch correctly

### ISSUE THREAD

**Issue by renaclerican35** [sabrogden/Ditto#648]
Hi !

When I launch Windows 11, Ditto appears in the taskbar but disappears when Windows finished to start.

Thank you for your help.

**Comment by sabrogden** [comment]
Can you manually start Ditto after Windows starts?  Are there any files in the folder, C:\Users\<user name>\AppData\Roaming\Ditto\Dumps, if so zip and upload them.

**Comment by renaclerican35** [comment]
Yes, I can manually start Ditto.

**Comment by sabrogden** [comment]
Can you enable logging to file by going to options - general - advanced - "Write debug to file" = true, this will write to the file C:\Users\<user name>\AppData\Roaming\Ditto\Ditto.log.  Restart and upload the file.

![image](https://github.com/sabrogden/Ditto/assets/16867884/5040a711-4ec8-4db1-a622-dfee1e1a3043)

**Comment by renaclerican35** [comment]
[Ditto.log](https://github.com/sabrogden/Ditto/files/14846619/Ditto.log)

**Comment by renaclerican35** [comment]
this log is the good !
[Ditto.log](https://github.com/sabrogden/Ditto/files/14847802/Ditto.log)

**Comment by sabrogden** [comment]
What time did you restart?  The only thing that stands out is

Ditto is already running, closing, mutex: Ditto Is Now Running
ExitInstance

Do you have multiple versions running?

**Comment by renaclerican35** [comment]
Restart took 2 minutes. I haven't multiple versions.

**Comment by sabrogden** [comment]
What clock time did you restart, there are 6 restarts in the log file, what one is the computer restart example?

**Comment by jlssmt** [comment]
same problem here
also win11

**Comment by garoto** [comment]
The `taskbar class` in Win11 is a hard change. See how `7 taskbar tweaker` doesn't support win11? Yeah. See if using https://github.com/valinet/ExplorerPatcher/ changes anything.

**Comment by renaclerican35** [comment]
Explorer patcher changes nothing.
I noticed that it was the same as Steam’s startup.

**Comment by jlssmt** [comment]
@renaclerican35 why did you close the issue?
Did you fix it.
The problem still occurs and is very frustrating.
