### ISSUE TITLE
Creation date incorrect at manual clip creation

### ISSUE THREAD

**Issue by Rainroom69** [sabrogden/Ditto#68]
.... as title mentions, when creating a new clip via CTRL + N the 'creation date' is set -in my case- as **1/01/1970 1:00:00**
Found when sorting in 'Delete clip data' list window.

Aside of the above ;
Is it possible to extend this list with the 'Quick paste text' field.  Easy to find which clips contains a value.  Thanks to consider.

**Comment by sabrogden** [comment]
I'll look at fixing both of these

**Comment by sabrogden** [comment]
https://ditto-cp.sourceforge.io/beta/
