### ISSUE TITLE
Indent behavior

### ISSUE THREAD

**Issue by GrampaWildWilly** [sabrogden/Ditto#683]
I have wondered idly for a long time about this behavior but never asked about it.  It's finally gotten the better of me so now I'm asking.  Here's what I observe:

![#01](https://github.com/sabrogden/Ditto/assets/75588964/08d2b953-f57c-48c5-9fc7-c62a42b5cb5a)
![#02](https://github.com/sabrogden/Ditto/assets/75588964/172e8c64-0f83-4b90-82dc-330f59fe2cc6)
![#03](https://github.com/sabrogden/Ditto/assets/75588964/13762eaf-a006-4fe6-801b-ac3b84b9f81a)

I would not say this rises to the level of a bug.  But it strikes me as a mildly odd behavior.  I should think either every clip should be indented or no clips should be indented, not this mix.  In case you're wondering, all the rest of my clips off screen to the bottom of the aperture I'm showing in my images are also not indented.

I'm just curious to hear what you think of this.

**Comment by garoto** [comment]
It's controlled by the highlighted option below:

![screenshot-0969-16-06-2024](https://github.com/sabrogden/Ditto/assets/11768175/2736d177-3084-454e-bee9-b136a1276c2c)

**Comment by GrampaWildWilly** [comment]
Thank you!  That doesn't seem entirely obvious.  The text for ALL my clips is displayed when I open the Ditto dialog, as you can see in my images.  I haven't defined 10 hot keys, just the one key sequence for opening the Ditto dialog.  But yes, that setting does make the dialog show all clips not indented.  I wasn't particularly looking to make that the case.  I was just curious what was going on.  But thanks again for the tip.

**Comment by GrampaWildWilly** [comment]
I'm trying to close this & mark your post as the answer.  I can do that in another forum on GitHub that I participate in.  But it doesn't seem to be working here.  Oh well . . .

**Comment by garoto** [comment]
Marking a reply as 'answer' only works on a repo's /discussions/. GH /issues/ tracker doesn't have that since it serves different purposes. But you can stil close your own issues no problem.

**Comment by GrampaWildWilly** [comment]
OK.  Let me try to close it again.
