### ISSUE TITLE
Drag clip to explorer folder gives warning

### ISSUE THREAD

**Issue by Rainroom69** [sabrogden/Ditto#70]
When dragging a clip to an explorer folder, a text_9xx.txt file is created, already when you still keep the left mouse button still pressed.  When releasing the left mouse button an warning popup windows mentions an aborted action.  "The name of the source file is the same as the target" ...

**Comment by sabrogden** [comment]
Does this happen anytime you drag to file explorer.  Are you dragging to a folder that requires admin access?

If you are not dragging a copied file format Ditto will create a file that contains the contents of a clip as a file, ctrl - drag to force this to happen.

**Comment by Rainroom69** [comment]
no longer happening/
