### ISSUE TITLE
[BUG/FEATURE REQUEST] Save position of clipboard history window across different machines

### ISSUE THREAD

**Issue by roblatour** [sabrogden/Ditto#710]
First, let me say I am running Ditto in what may be a non-standard way - accordingly, I don't know if this is a bug or a feature request :-)

**Setup:**
I have three Windows computers, all running Ditto and in order to facilitate working between them, I have put the Ditto clipboard database on a shared network drive, and I have set the location of the ditto database on each machine to point to the same common database.

This allows me to copy something on one machine and then easily paste it on another machine.   

However, and I'm not sure if it is related or not to this setup, but when I open up the Ditto history window on one machine I have it positioned to the far right, and nearer the bottom of the screen, and whenever I open and close the Ditto history window on that machine it stays in that location (where I want it to).  However, when I open and close it on the other machines it is always centred in the middle of the screen.  I can move it on those screens, but on those two other machines it always opens up in the middle of the screen regardless.

**Request:**
It would be nice if Ditto's history window could open at the location and be the same size as it was when it was last closed on each machine independently.

Thanks for the great tool!

**Comment by PzaThief** [comment]
Hello.
It looks like you are using different options for each desktop.
The popup position settings shown on the first configuration page are stored in each desktop's registry, not in the database.
So could you please check the options again?

**Comment by roblatour** [comment]
@PzaThief Wow, so silly of me.  Of course you are right.  Thank you.
