### ISSUE TITLE
draw color code expansion request

### ISSUE THREAD

**Issue by indigofairyx** [sabrogden/Ditto#722]
this is a fantastic feature! very helpful when working on a design project.

could it be expanded upon to draw any set of 3 number even out of (brackets) or without a hex #264 

 e.g.

`255,185,0` and `RGB(255,185,0)` would both draw a color
and
`FFB900` and `#FFB900`

![image](https://github.com/user-attachments/assets/4885cb23-7263-4dfe-bb75-760994ad89a1)

![image](https://github.com/user-attachments/assets/ef89b7ea-9bbe-452b-a561-e47c04bd7ca2)

thanks!
xavier

**Comment by sabrogden** [comment]
Please try the latest and verify this is what you want, https://github.com/sabrogden/Ditto/releases

**Comment by indigofairyx** [comment]
awesome! Thank you! Seems to working with hex & rgb, with and without `#`(symbols) and\or spaces in the rgb.

😀 
thank you again

![image](https://github.com/user-attachments/assets/fbff7e08-b590-4560-aed7-dce4c96d8993)
