### ISSUE TITLE
keyboard shortcuts for navigating up/down?

### ISSUE THREAD

**Issue by maxgerman** [sabrogden/Ditto#731]
Hi. I'd very much like to use customizable up/down keys (like JK vim-style, for example) and haven't found these in settings. Can this be added?

**Comment by c137-hacker-rick** [comment]
Agreed!

**Comment by ConnorHibbs** [comment]
Have you tried the "Move Selection Up" and "Move Selection Down" key bindings in the Quick Paste Keyboard options?

(Activate Ditto), click the 3 dots in the lower right hand corner, click "Options". On the Quick Paste Keyboard tab, these options are  about 1/3 of the way down.

![image](https://github.com/user-attachments/assets/8407d405-cdfc-48bc-a5a5-eb7fc73f4ffc)
