### ISSUE TITLE
Typo in Advanced Settings.

### ISSUE THREAD

**Issue by wangyuew** [sabrogden/Ditto#75]
First Ten Hot~~H~~Keys Start Index
First Ten Hot~~H~~Keys Font Size

**Comment by sabrogden** [comment]
Thanks, fixing this now

**Comment by CaptainFrosty** [comment]
@sabrogden 

There's another at the bottom of advanced settings:

![image_11](https://user-images.githubusercontent.com/8523498/147521240-9d174ca0-7629-4e54-9a6a-b67861bcbb99.png)
