### ISSUE TITLE
Disable 'friends' / networking features, completely.

### ISSUE THREAD

**Issue by xcasxcursex** [sabrogden/Ditto#80]
Is it possible to completely disable any sharing/network functionality of the application?

I am aware of the option to disable receiving clips, I also want to disable sending them, and any other reason the app might touch the network.

Related: https://sourceforge.net/p/ditto-cp/discussion/287511/thread/e2f9316b/
This thread asks the same question and is answered by a link to documentation which has been removed.

**Comment by sabrogden** [comment]
Friends can be turned off by a config setting, sorry have to modify the registry or ini file for this.  I'll look at adding an advanced ui setting to make it easier.

https://github.com/sabrogden/Ditto/wiki/Restrict-Config-Settings

**Comment by sabrogden** [comment]
Added option in options - general - advanced - Disable friends

https://ditto-cp.sourceforge.io/beta/

**Comment by xcasxcursex** [comment]
Thanks mate, you're a legend!
