### ISSUE TITLE
Clipboard entries only numbered up to ten

### ISSUE THREAD

**Issue by wkdpower** [sabrogden/Ditto#82]
Is is a bug or a setting that I can't find? The list of clips in Ditto are numbered 1-9, then 0, then any entries below that aren't numbered at all.

![Ditto](https://user-images.githubusercontent.com/9849923/110880767-0a75bd80-82d7-11eb-921e-8b0629e4d375.jpg)

**Comment by sabrogden** [comment]
That just shows a quick way to paste the first ten entries.  So ctrl-1 would paste the first slot and so on.  You can change these shortcuts in options - quick paste keyboard - Paste Position 1/2/3/...

If you don't want to see these number you can hide them in options - general - advanced - "show text for first ten copy hot keys" = False

![image](https://user-images.githubusercontent.com/16867884/111881599-bf167b80-8976-11eb-9f7a-dd8bf5faba77.png)

**Comment by wkdpower** [comment]
Ah, that makes sense, I hadn't realised that's what the numbers were for. Hiding them does the trick for me. Cheers.

**Comment by Chealer** [comment]
It might help if, when hovering a number, a tooltip indicating the shortcut (say <kbd>Ctrl</kbd>+<kbd>2</kbd>) would show.
