### ISSUE TITLE
Ditto has stopped working for me

### ISSUE THREAD

**Issue by NancyLebovitz** [sabrogden/Ditto#87]
It no longer saves what I've copied. Unfortunately, I don't remember when the problem started. Probably a week or two, it might have been after the most recent update.

I've tried uninstalling and reinstalling it.

I'm using Windows.

**Comment by treeowl** [comment]
I suggest you indicate which version of Windows, and explain in detail: 1. What did you do? 2. What did you expect to see? 3. What did you actually see?

**Comment by NancyLebovitz** [comment]
Windows 10. 

What I expect-- click on the ditto icon on the lower right. Popup should appear with short versions of things I've copied recently. It has a search window to find things I've copied further in the past.

What I'm getting now-- when I click on the icon, the popup appears, but there's no text in it. The main part of the popup is light gray, but the search box shows up as white when I click on where it should be. When I type in the search window, I don't see any letters, but scroll bars appear.

There may be something wrong with Windows failing to show text-- chat in Zoom was blank today (or with grayed out rectangles, I think). This is a problem I haven't had before.

**Comment by NancyLebovitz** [comment]
I've rebooted, and Ditto has at least started to work-- it's saved a couple of items.

It has mysteriously started appearing in the upper right hand corner (less convenient), but I'll start another ticket if this persists.

Thanks very much.

**Comment by pmkdatabase** [comment]
What is the uninstall procedure? I do not see ditto in my program list. 

Thanks

**Comment by NancyLebovitz** [comment]
I'm not sure what you're asking. I only have Ditto because I installed it-- it doesn't come with Windows. 

Let me know if that doesn't answer your question.
