### ISSUE TITLE
Clean clips except items in groups

### ISSUE THREAD

**Issue by git-guppio** [sabrogden/Ditto#9]
Goodmorning everyone.
Is it possible to delete the items present in the clip except for those inserted in the group?
Usually I clean up the clip by selecting all items pressing {CTRL + A} and then pressing {DEL}.  However, this also deletes the data in the groups. It is possible to delete only those not contained in the groups?

Thank you very much and congratulations for this very useful program!

**Comment by sabrogden** [comment]
In the latest you can click on the ... - Delete All Non Used Clips.  This will delete all clips that are not a group, in a group, not auto delete, shortcut key set, or sticky.  You can assign a shortcut key if needed in options - quick paste keyboard
