### ISSUE TITLE
Delete Problem

### ISSUE THREAD

**Issue by HBoyter** [sabrogden/Ditto#95]
I restored a db, created a Group, and moved the entries into that group. However, instead of moving the entires, they were duplicated in the Group and main window. Now, I can not delete an entry in the group without it deleting it in the main window too and the same happens in reverse. Any help?

**Comment by sabrogden** [comment]
By default all clips are shown in the top level clip list.  This can be turned off by going to options - general - advanced - "Show clips that are in groups in main list" = False

![image](https://user-images.githubusercontent.com/16867884/111880387-e1a59600-8970-11eb-905f-671a6abbd1db.png)

**Comment by HBoyter** [comment]
Thanks. That is hard to find when you do it once every couple of years.
