### ISSUE TITLE
Feature Request: New CLI flag for "Compact And Repair Database"

### ISSUE THREAD

**Issue by ronstudy1** [sabrogden/Ditto#98]
I use to run a script that "Compact And Repair Database". I run it nightly when outside of work hours.
Since this action is possible only though GUI then i have a script that opens ditto's "Advanced Options" and clicks on the suitable button.
It could be great if this can be done through CLI instead

Thanks!

**Comment by ronstudy1** [comment]
Any plans to support this feature?

**Comment by garoto** [comment]
Try vacuum the `ditto.db` with the `sqlite3.exe` binary avaiable from their website:

 `sqlite3.exe C:\My\Path\To\Ditto\Ditto.db "VACUUM;"`

Better to shutdown `Ditto` before trying, just in case you have no .DB backups. Can be easily scripted with batch files and whatnot.

**Comment by ronstudy1** [comment]
actually, the built-in Compact also deletes old entries before the "VACUUM;" command ([code](https://github.com/sabrogden/Ditto/blob/8822302339128b1c1da6c4096df2257b6f28726d/AdvGeneral.cpp#L949))
so it's only a half-solution
manually executing SQLs for deleting old entries is already too complicated. therefore i would really like to have Ditto support a new command line flag to compact the database
